### ISSUE TITLE
win10  init fail

### ISSUE THREAD

**Issue by feng003** [lavas-project/lavas#1]
I can't import the demo name.I don't kown this question is system(win10) or lavas ?

**Comment by PengXing** [comment]
能详细描述一下是在哪个阶段出的问题吗？错误信息或者截图都可以

**Comment by feng003** [comment]
![image](https://user-images.githubusercontent.com/3939670/27903111-b2f6cfda-626a-11e7-8c30-3fca4b92c85d.png)
不能输入名称

**Comment by PengXing** [comment]
由于我们暂时没有 win10 的机器，晚上回去看一下，另外项目名称需要符合 [npm 的 package.json 里的 name 字段的命名规范](https://docs.npmjs.com/files/package.json#name)

**Comment by PengXing** [comment]
能否尝试一下输入英文的项目名呢？

**Comment by PengXing** [comment]
我先关掉这个 issue 了，如果有进一步的反馈，再重新打开吧
