### ISSUE TITLE
多个第三方组件在mobile模式下，点击失效

### ISSUE THREAD

**Issue by xcheese** [lavas-project/lavas#111]
复现步骤
1、lavas init  ssr模式
2、npm install vue-multiselect   //https://github.com/shentao/vue-multiselect
3、在 Index.vue中
      `<multiselect v-model="value" :options="options"></multiselect>`

`data () {
        return {
            value: null,
            options: ['list', 'of', 'options']
        }
    },`

在ios下，safari中，无法点击，一样的代码，但是官方的demo是可以的

**Comment by easonyq** [comment]
lavas 中默认添加了 FastClick，应该是这两个类库的冲突。如需去掉，可以在 `entry-client.js` 中将它注释掉。

```javascript
// import FastClick from 'fastclick';
// FastClick.attach(document.body);
```
