### ISSUE TITLE
路由keepalive 为什么会同时走created activited

### ISSUE THREAD

**Issue by jamninetyfive** [lavas-project/lavas#112]
lavas的  keepalive 问题 

情况如下(最新版本)

1.首先存在两个页面 ，首页 和 detail页

2.设置detail 不keepalive  index keepalive  

3.出现问题 index 或者detail 页面 返回操作会乱触发 created activited 周期  同时触发两个周期正常来讲是不应该触发两个的 被keepalive的 created是不应该触发的 

lavas.config.js route配置如下

routes:[
            {
                pattern: /\/detail/,
                lazyLoading: true,
                meta: { 
                    keepAlive:false
                }
            },
            {
                pattern: /\/.*/,
                lazyLoading: true,
                meta: { 
                    keepAlive:true
                }
            },
        ]

**Comment by xiaoiver** [comment]
确实是一个 Bug，修复方法如下：

**Comment by guchunwen** [comment]
`<keep-alive :include="['index','detail']">//可以通过路由的name去配置是否需要keepAlive
           <router-view
            :key="$route.fullPath"
           class="app-view"
           :class="[pageTransitionClass]"
           ></router-view>
</keep-alive>`

**Comment by guchunwen** [comment]
`<pre></pre>`

**Comment by guchunwen** [comment]
```js
<keep-alive :include="['index','detail','mine']">//可以通过路由的name属性去配置是否缓存
        <router-view
            :key="$route.fullPath"
           class="app-view"
           :class="[pageTransitionClass]"
          ></router-view>
</keep-alive>//这样不需要写两次router-view，并且也不需要配置路由的meta

**Comment by xiaoiver** [comment]
如果不想使用 Lavas 提供的对于 keep-alive 切换的配置，完全可以使用 @guchunwen 的方法直接修改 `core/App.vue` ，省掉不必要的模版节点。但是不要忘记给路由组件设置名称。

**Comment by xiaoiver** [comment]
这个确实是一个 Bug，出现在从非 keep-alive 组件切换回 keep-alive 组件后，原本缓存的内容被丢弃，会再次执行 created。参考 [ISSUE](https://github.com/vuejs/vue-router/issues/811)

 在@guchunwen提出的[方法](https://github.com/lavas-project/lavas/issues/112#issuecomment-375582808)基础上，继续保留 `keepAlive` 的配置，Lavas 会根据配置生成一份开启 `keepAlive` 的路由名单：
```html
// core/App.vue
<keep-alive
    :include="[...keepAlivePages]">
    <router-view
        class="app-view"
        :class="[pageTransitionClass]"
        ></router-view>
</keep-alive>

import {keepAlivePages} from '@/.lavas/router';
```
