### ISSUE TITLE
lavas init 下载 Lavas 模版出错

### ISSUE THREAD

**Issue by masktim** [lavas-project/lavas#113]
rt。模板拉取失败。请问还有其它方式么？？能否单独离线模板???

**Comment by easonyq** [comment]
您的网络有问题是么？所以一直无法 `lavas init`？

如果的确是网络问题想采用离线方式，可以下载我们的 [lavas-template-vue](https://github.com/lavas-project/lavas-template-vue) 项目的 `release-basic` 分支进行开发，算是没有办法的办法吧。

**Comment by sunYanxl** [comment]
![image](https://user-images.githubusercontent.com/15374553/44706355-e0bb6900-aad3-11e8-9469-a76ae10a26a5.png)
网络是ok的，为啥一直这样。

**Comment by sunYanxl** [comment]
网络正常，可以流畅的访问git，lavas 2.2.9

**Comment by zoumiaojiang** [comment]
从报错信息看就是请求 github timeout，有一些开发者也遇到过这个问题，但是我们又不能稳定复现，所以我们准备放弃从 github 上拉取模版，新方案在近期会随新版发出。:P

**Comment by zwl1619** [comment]
1、我也遇到这个问题了，lavas init生成不了项目文件夹。

2、版本号是否没有修改？github上master分支的版本号是2.1.9，npm官网是2.2.9，发版时间是一个月以前。
