### ISSUE TITLE
关于vuex无法更改state

### ISSUE THREAD

**Issue by bluegeek** [lavas-project/lavas#117]
lavas脚手架的问题。
使用store的时候可能没有vue实例，但是如果按照目前的写法，会无法更改state
我认为core目录下应该加一个store.js
```
import { createStore } from '../.lavas/store'

const store =createStore()
export default store
```
然后在App.vue里面引入。
每次使用store的时候 ，引入store.js就可以了，而不是直接引入.lava目录下的。

可能有别的方式，一点建议。

**Comment by easonyq** [comment]
`store.js` 原本的确是在 `core` 目录下的，和 `app.js` 等一起供开发者修改。但经过几个月的反馈，似乎并没有开发者有修改它的需求。出于精简目录，避免开发者望而生畏的考虑，我们就把 `store.js` 改为自动生成，放到了 `.lavas` 目录里面去了。

您是要修改 store 具体的什么内容？
