### ISSUE TITLE
直接npm安装的js-beautify不完整

### ISSUE THREAD

**Issue by vanishcode** [lavas-project/lavas#12]
使用app-shell模板创建的基础工程dev跑不起来，发现缺少模块。npm i 安装后js-beautify目录下只有js一个文件夹，缺少大部分依赖，然后直接去主页下了一个怼到了module里。。
（话说好像这不是你们的锅。。）

**Comment by dear-lizhihua** [comment]
是这个问题？
https://github.com/beautify-web/js-beautify/issues/1247
