### ISSUE TITLE
 multiple dynamic segments

### ISSUE THREAD

**Issue by stkevintan** [lavas-project/lavas#122]
2.x的Lavas根据路径自动生成路由，那官网的这种形式的动态路由该怎么实现？

pattern | matched path | $route.params
-- | -- | --
/user/:username/post/:post_id | /user/evan/post/123 | { username: 'evan', post_id: 123 }

**Comment by xiaoiver** [comment]
文件夹名称也可以以下划线开头，表示动态参数。
这里建一个 `_username` 的文件夹就 OK 了。
