### ISSUE TITLE
lavas ssr部署https模式下查看网页源代码没有生成ssr代码

### ISSUE THREAD

**Issue by longFeiLi** [lavas-project/lavas#123]
从官方脚手架下载的项目：
目前项目git: **https://github.com/longFeiLi/lavas-project**

pc谷歌浏览器
**view-source:https://www.lovell.com.cn/**
结果没有带出ssr代码

nginx配置如下
![image](https://user-images.githubusercontent.com/10267141/38187802-bd12bc2c-368b-11e8-8076-0689e47b23a8.png)

但是奇怪的是:view-source:http://www.lovell.com.cn/
不加https就可以显示出来

![image](https://user-images.githubusercontent.com/10267141/38187939-525a6b18-368c-11e8-848a-d291916f2190.png)

![image](https://user-images.githubusercontent.com/10267141/38187952-60a64b42-368c-11e8-9009-14e46dd7ea41.png)

**Comment by PengXing** [comment]
其实是这样的，这正是我们目前的策略起的作用，在 https 下，service worker 注册成功了，下次访问的时候会优先用 service worker 事先请求的 /appshell 来渲染，然后再请求服务器端的数据来渲染

你可以试一下把 service worker unregister 掉再查看源代码，就是有内容的，如果有问题，可以再回复
