### ISSUE TITLE
lavas start failed

### ISSUE THREAD

**Issue by stkevintan** [lavas-project/lavas#127]
lavas build 之后执行lavas start出现如下错误。
```
⠋ [Lavas build] start reading config...{ Error: ENOENT: no such file or directory, open '/home/kevin/Project/yx-pwa/lavas/config.json'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/kevin/Project/yx-pwa/lavas/config.json' }
```

查看源码发现在`lavas-core-vue/core/utils/path.js`中有如下定义：
```js
/**
 * concat with lavas dir
 *
 * @param {string} rootDir rootDir
 * @param {string} path path
 * @return {string} resolved path
 */
export function distLavasPath(rootDir, path) {
    return join(rootDir, LAVAS_DIRNAME_IN_DIST, path);
}
```
这里rootDir传的是process.cwd()也就是项目根目录，path是"config.json" , 而在constant文件里：
```js
export const LAVAS_DIRNAME_IN_DIST = 'lavas';
```
所以这个函数的返回路径是`/lavas/config.json` ，这是不存在的。首先根目录里面只存在`/.lavas`，然后如果指的是`/dist/lavas`的话，这个目录里面是没有`config.json`的。

**Comment by easonyq** [comment]
首先，`lavas start` 命令的使用方法是在 `lavas bulid` 之后 __cd 到 `dist` 目录后__ 再执行的，所以你一开始的用法就不太对。这个官方文档上也有说明的。

![image](https://user-images.githubusercontent.com/6800839/38462422-a09027f0-3b19-11e8-91ea-dce1f30c1457.png)

其次，根据你说的 `/dist/lavas/config.json` 不存在的问题，我怀疑你开发的是 SPA 项目，因此应该使用 `lavas static` 而非 `lavas start`。参考文档的这一部分：

![image](https://user-images.githubusercontent.com/6800839/38462464-439c9bb8-3b1a-11e8-9ae0-f80b904a45ac.png)

判断是否 SPA 项目也很简单，看一下自己根目录下 `lavas.config.js` 中 `build.ssr` 是 `true/false` 即可。

最后附上文档链接，如有问题我们再联系。

[Lavas 命令介绍](https://lavas.baidu.com/guide/v2/basic/cli)

**Comment by stkevintan** [comment]
明白了，谢谢回答
