### ISSUE TITLE
在iPhone手机上，没有更新后的提示

### ISSUE THREAD

**Issue by SmarkSeven** [lavas-project/lavas#13]
应用更新后，在iPhone手机上，没有更新后的提示，Safari和Chrome都没有，Android没问题。

**Comment by zoumiaojiang** [comment]
这是因为目前 iOS 系统不支持 service worker 特性，由于操作系统层面的原因，iOS 所有的浏览器都是和 safari 的支持情况保持一致的。目前大多数 android 手机是支持 service worker 的
