### ISSUE TITLE
router.js 需要增加灵活性

### ISSUE THREAD

**Issue by easonyq** [lavas-project/lavas#132]
Lavas 的一大特色功能是根据 pages 目录中的结构来生成对应的路由规则，避免开发者重复声明。这个功能是通过自动生成 router.js （位于 .lavas/router.js） 来实现的。在开发者的代码 (lavas-template) 中的 /core/app.js 中，通过暴露的 `createRouter()` 方法创建 `router` 并提供给 Vue 进行后续使用。

但因为是生成的代码，方便的同时牺牲了灵活性。目前的 router.js 中主要包含如下内容：

1. 自动生成的路由规则（数组）
2. 翻页动画相关（通过 `scrollBehavior` 和 router 的钩子实现）
3. keepAlive 的页面集合（数组）__（已 export）__
4. `createRouter` 方法创建 `router` 对象 __（已 export）__

考虑如下需求，现行状态下就很难实现：

1. 开发者对自动生成的路由规则（或某一部分）不满意
2. 开发者希望对自动生成的路由规则添加配置项不支持或者不包括的功能（如 `route.redirect` 项希望传入方法）
3. 开发者对自动生成的翻页动画特效不满意

核心原因是四个部分集中在一起，如果开发者对某一块不满意，必须 __重写__ router.js，即放弃 Lavas 的部分功能。

我们应该考虑将这几块分开，能够独立提供给开发者引用，以实现个性化的需求。

**Comment by RYUDEN** [comment]
![image](https://user-images.githubusercontent.com/23655870/39914390-7ed27978-5537-11e8-86ae-9f606f637bac.png)
在CITY里面有几个页面这种情况。city里面会有几个页面，如果_city文件夹中包含index文件会影响整个项目展示，如何在用户输入/:city 的情况下跳转进入/:city/page 呢？

**Comment by easonyq** [comment]
@RYUDEN 
> 如何在用户输入/:city 的情况下跳转进入/:city/page 呢？
我不一定100%理解了你的问题。我尝试回答一下我理解的版本，如有误解希望你继续补充~

我猜测你的问题是 如何配置让用户输入 `/shanghai` 跳转到 `_city/page.vue`？

如果是这个问题，可以使用路由的 [rewrite配置](https://lavas.baidu.com/guide/v2/advanced/router#%E4%BD%BF%E7%94%A8-rewrite-%E4%BF%AE%E6%94%B9%E8%B7%AF%E7%94%B1%E8%B7%AF%E5%BE%84)

如果不是，麻烦举个例子说明一下？谢谢！
