### ISSUE TITLE
配置 babel-loader 的方式

### ISSUE THREAD

**Issue by xiaoiver** [lavas-project/lavas#142]
## 问题描述

项目中有两处使用 `babel-loader` 的地方：`vue-loader` 和处理 `.js` 的规则。但是配置 `babel-loader` 的地方却存在两处：项目根目录下 `.babelrc` 和 `lavas.config.js` 中的 `build.babel` 配置项。

## 解决方案

首先 babel-loader 有两种配置方式：
1. `.babelrc`
2. `babel-loader` 传入 `options` 参数

Lavas 默认使用 `presets: ['vue-app']`，同时根据当前是 SPA 还是 SSR 传入不同的 `targets`（SSR 为 `{node: 'current'}` SPA 为 `{ie: 9, uglify: true}`）。这样只会引入当前环境所需要的 babel polyfill。
可见一旦采用这种方式，`.babelrc` 就不适合了。

另外 `vue-loader` [推荐使用](https://vue-loader.vuejs.org/zh-cn/features/es2015.html) `.babelrc`，但还是可以通过配置项把 babel-loader 的参数传进来。

### 使用 `build.babel`

默认方式，在 `lavas.config.js` 中扩展，例如添加 `plugins`
```js
// lavas.config.js

build: {
  babel: {
    plugins: ['xxxx']
  }
}
```

### 使用 `.babelrc`

首先开启 `.babelrc`
```js
// lavas.config.js

build: {
  babel: {
    babelrc: true
  }
}
```

然后配置 `presets`，根据项目是 SPA 还是 SSR 配置 `targets`。随意引入 `plugins`
```json
// .babelrc

{
    "presets": [
        "vue-app",
        {
            "targets": {"ie": 9, "uglify": true}
        }
    ],
    "plugins": [
        "transform-runtime",
        ["transform-imports",
            {
                "vuetify": {
                    "transform": "vuetify/es5/components/${member}",
                    "preventFullImport": true
                }
            }
        ]
    ]
}

```

**Comment by easonyq** [comment]
我想了一下，觉得大部分开发者应该是更习惯去编写 `.babelrc` 而非我们的配置项，毕竟 `.babelrc` 不止 lavas 或者 vue，应该是更多项目的 __推荐__ 配置方式。

因此我建议是不是能把 `.babelrc` 设置为默认方式，而不是 `lavas.config.js`？考虑一下？ @xiaoiver
