### ISSUE TITLE
Lavas 如何使用 Notification API 弹出通知

### ISSUE THREAD

**Issue by easonyq** [lavas-project/lavas#145]
*这个问题由开发者提出*

## 问题描述

有开发者希望使用 Notification API 来给用户弹出通知。根据[文档](https://lavas.baidu.com/pwa/engage-retain-users/notification/notification-introduction)，所有的通知都需要事先拿到注册 Service Worker 时的回调对象 `registration` 才能继续，如

```javascript
function registerServiceWorker() {
    return navigator.serviceWorker.register('service-worker.js')
    .then(registration => {
        console.log('Service worker successfully registered.');
        return registration;
    })
    .catch(err => {
        console.error('Unable to register service worker.', err);
    });
}

function execute() {
    registerServiceWorker().then(registration => {
        registration.showNotification('Hello World!');
    });
}
```

而在 Lavas 中，Service Worker 是由 [sw-register-webpack-plugin](https://github.com/lavas-project/sw-register-webpack-plugin) 这个插件负责注册的，因此是 __全封闭__ 的，开发者也暂时没有办法获取到这个 `registration` 对象，自然也没办法使用通知 API 了。

## 解决方案

我们虽然无法在注册 Service Worker 的第一时间来获取到 `registration` 对象，但我们可以通过其他方法来获取它，如下：

```javascript
navigator.serviceWorker.ready.then(reg => {
    // use reg.showNotification here
})
```

这段代码可以放置在 `core/spa.html.tmpl` 或者 `entry-client.js` 里面，只要是在浏览器的环境中即可。

__不要忘了发送通知前先获取权限！__

**Comment by xiaoiver** [comment]
补充一下 [MDN 相关文档](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/ready)
