### ISSUE TITLE
init appshell 工程，npm run dev后出现下面的问题

### ISSUE THREAD

**Issue by ChaoLeer** [lavas-project/lavas#15]
![default](https://user-images.githubusercontent.com/25276032/31700037-3e23fddc-b3f9-11e7-8eef-14a81a62ba68.png)

是vuetify包里面报的，不确定是否是vuetify自身的问题还是lavas的问题，麻烦请组织帮忙验证一下，更新了vuetify版本也不起作用

**Comment by liuruoran88** [comment]
您好，感谢您提出的问题，问题已定位修复，（1）定位原因： vuetify 0.15 版本组件按需加载需要在 webpack 中配置`node_modules/vuetify` 路径的 babel-loader，而 cnpm install 把 node_modules 中的文件夹名称做了修改，和 npm install 前面配置的路径有差别，导致 webpack 打包错误。（2）问题修复： vuetify 升级 0.16 版本修复了这个问题， 我们也在升级了版本，更新了模板配置代码，您可以再次尝试 lavas init 使用，再次表示感谢 ！！^_^
