### ISSUE TITLE
lavas 和 nuxt 有什么区别呀

### ISSUE THREAD

**Issue by webKity** [lavas-project/lavas#155]
lavas 和 nuxt 有什么区别呀，我看和nuxt没有什么区别

**Comment by easonyq** [comment]
nuxt 是一款基于 Vue 的 __服务端渲染__ 框架，因此它侧重于帮助用户完成 Vue SSR 项目的快速搭建。

lavas 的核心是 __帮助站点拥有 PWA 的特性__。但为了方便，也提供了用户从无到有的快速搭建项目的功能。而且实际上 lavas 在 SSR 的部分逻辑的确参考了 nuxt 的实现方式。

事实上如果您想搭建一个 Vue SSR 项目并实现 PWA 相关功能，有两种做法：
1. 使用 nuxt 搭建项目，并且额外逐个添加 PWA 的功能，如 Manifest, Service Worker 等等
2. 使用 lavas 搭建项目，使用配置项快速完成 PWA 功能

具体哪个方便就看您自己的选择了。
