### ISSUE TITLE
lavas start的时候报错，提示找不到config.json文件，具体如下

### ISSUE THREAD

**Issue by webKity** [lavas-project/lavas#156]
`[Lavas build] start reading config...{ Error: ENOENT: no such file or directory, open '/Users/chenyongqin/study/project/lavas/lavas/config.json'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/chenyongqin/study/project/lavas/lavas/config.json' }`

**Comment by PengXing** [comment]
可能的原因有两个

1. 请到 dist 目录运行
2. ssr 才支持 `lavas start`，spa 项目用 `lavas static` 运行

**Comment by easonyq** [comment]
@webKity 如果是第二个原因给开发者造成的混淆，我们已经有打算要统一这两个命令，您可以关注一下 [这里](https://github.com/lavas-project/lavas/issues/154)

**Comment by PengXing** [comment]
https://github.com/lavas-project/lavas/issues/154
