### ISSUE TITLE
mac lavas init fail

### ISSUE THREAD

**Issue by qiano** [lavas-project/lavas#16]
不能输入名称
<img width="572" alt="2017-10-24 12 45 21" src="https://user-images.githubusercontent.com/973497/31925145-449fe35a-b8b9-11e7-88eb-bb6941c42f85.png">

**Comment by PengXing** [comment]
你这个问题还真是没遇到过，是输入法的问题吗？关掉重开一次试试？

**Comment by qiano** [comment]
应该不是输入法的问题，不使用输入法同样无法输入。。我刚才又试了一遍

**Comment by PengXing** [comment]
那能反馈一下机器包括各种环境的版本号吗？我们来尝试复现一下

**Comment by qiano** [comment]
我用的是node v8.1
将node 版本切换到7就可以正常运行，是node兼容性问题

**Comment by PengXing** [comment]
我用的是 v8.1.3，也没问题 =。=

**Comment by qiano** [comment]
你再试试8.8.1行不行

**Comment by PengXing** [comment]
我也装了一下 8.8.1，可以正常运行。
![image](https://user-images.githubusercontent.com/527244/32478061-0a63a138-c348-11e7-8120-9a0c34584fb7.png)

**Comment by PengXing** [comment]
先关掉了，如果后续还有其他的信息，欢迎重新提

**Comment by qiano** [comment]
谢谢


原始邮件
发件人:PengXingnotifications@github.com
收件人:lavas-project/lavaslavas@noreply.github.com
抄送:QIANqshuai162@qq.com; Authorauthor@noreply.github.com
发送时间:2017年11月25日(周六) 23:11
主题:Re: [lavas-project/lavas] mac lavas init fail (#16)


先关掉了，如果后续还有其他的信息，欢迎重新提
