### ISSUE TITLE
请问如何在lavas.config.js里配置webpack？？

### ISSUE THREAD

**Issue by silence-may** [lavas-project/lavas#166]
你好，
我的模块里有依赖注入的变量名，项目构建以后，变量名被改变了。
Lavas 内置的插件中有
![image](https://user-images.githubusercontent.com/20940285/40264723-3c8536ba-5b5d-11e8-8a97-d1c95234ad87.png)
那请问我该如何配置这个插件呢???
我需要以下变量名不被混淆
            'Buffer',
            'BigInteger',
            'Point',
            'ECPubKey',
            'ECKey',
            'sha512_asm',
            'asm',
            'ECPair',
            'HDNode'
ps:通过文档我也尝试过在lavas.config.js的build中配置plugins，extendWithWebpackChain的内容，但是没有成功！！望回复！谢谢！

**Comment by PengXing** [comment]
线下 QQ 沟通已解决，我把解决方法写在这里

修改 lavas.config.js，在 build 中增加 `extendWithWebpackChain` 函数配置，参考 https://lavas.baidu.com/guide/v2/advanced/build-config#extendwithwebpackchain
```javascript
extendWithWebpackChain(config, {type, env}) {
    config.plugin('uglify-js').use(UglifyJSPlugin, [{
        parallel: true, // enable `parallel` option
        sourceMap: true,
        uglifyOptions: {
            mangle: {
                keep_fnames: true,
                safari10: true,
                reserved: ['Buffer']
            }
        }
    }]);
}
```
