### ISSUE TITLE
keepalives功能无效

### ISSUE THREAD

**Issue by aojianwu** [lavas-project/lavas#167]
从list到detail,再返回list，一直都是mounted
测试如下：
list.vue
```
<template>
    <div>
        <router-link to='/detail'>到detail</router-link>
    </div>
</template>


<script>
    export default {
      mounted() {
        console.log("list mounted");
      },
      activated() {
        console.log("list activated");
      }
    };
</script>
```
detail.vue
```
<template>
    <div>i am detail</div>
</template>




```

lavas.config.js 主要修改
```
    router: {
        mode: 'history',
        base: '/',
        pageTransition: {
            type: 'fade',
            transitionClass: 'fade'
        },
        routes: [{
            pattern: /\/list/,
            meta: {
                keepAlive: true
            },
        }]

    },



```

**Comment by easonyq** [comment]
你好。你的代码中有两个问题：

1. 最底下的配置中，只配置了 `/list` 为 `keepAlive: true`，而没有给 `/detail` 配置。
    不过这个并不是引发问题的根本，我估计更多的是写例子的时候遗漏了

2. __核心__：你的组件没有 export `name` 属性。给 `detail.vue` 和 `list.vue` 分别添加 `name` 属性即可解决问题。

根据 Vue 官方文档中 keepAlive 的[相关说明](https://cn.vuejs.org/v2/api/#keep-alive)
    
> 匹配首先检查组件自身的 name 选项，如果 name 选项不可用，则匹配它的局部注册名称 (父组件 components 选项的键值)。匿名组件不能被匹配。

你的情况属于匿名组件，因此 keep-alive 不对它产生效果。

**Comment by easonyq** [comment]
顺带在这里提一下，根据以上说明，keep-alive 需要两者相匹配，这两者分别为：
* 组件 export default 的 `name`
* 标记在 `<keep-alive>` 中的 `include` 属性

第一点很好理解，第二点因为 lavas 自动生成路由并且自动填写的关系，所以对用户其实是透明的。换言之 __用户无法修改__。那么在 lavas 中，用户能做的就是 __让每个组件的 `name` 和自动生成的路由对应__。

因此我们有必要了解一下 lavas 自动生成的 name 到底是什么规则。

核心原则只有一条：`name` 属性就是路径转化为驼峰。

具体来说：

1. 不包含动态参数的普通路径，如 `pages/Hello.vue`，则 `name` 等于 `hello`
2. 包含动态参数，如 `pages/detail/_id.vue`，那么 `name` 等于 `detailId`
3. 嵌套路由，如 `pages/User.vue` 存在，此时 `pages/user/Create.vue` 的 `name` 等于 `userCreate`，`pages/user/_id.vue` 的 `name` 等于 `userId`
