### ISSUE TITLE
支持 Vuex Plugin

### ISSUE THREAD

**Issue by easonyq** [lavas-project/lavas#169]
有开发者提出 ([问题](https://github.com/lavas-project/codelab/issues/12)), 目前的 Lavas 不支持 Vuex Plugin。

为了支持这个功能，我们需要重新将 `store.js` 从 `.lavas/store.js` 移动到 `core/store.js`，供用户自行修改。这个功能将会在下一个版本中添加。

届时除了更新 lavas-core-vue 到最新版本之外，还需要重新 lavas init 项目（因为模板改变了）。

不需要使用这个功能的开发者不用重新初始化项目。__更新 lavas-core-vue 到最新版本也不影响使用__

**Comment by trionfo1993** [comment]
在/store底下新建一个index.js
```javascript
export default {
    plugins: []
}
```
就可以使用plugins了

**Comment by trionfo1993** [comment]
这个是文档的问题，和nuxt.js一样 不去翻阅源码没办法发现这个方法
