### ISSUE TITLE
lint 有一堆的错误

### ISSUE THREAD

**Issue by dingquantracy** [lavas-project/lavas#17]
我觉得吧，既然是demo，跑起来最好不要有错误，实在不行可以放宽校验的标准吧，😄😄😄

fecs  INFO src/App.vue (3 messages)
fecs ERROR → line 55, col 1: Missing JSDoc @file.	(fecs-valid-jsdoc)
fecs ERROR → line 55, col 1: Missing JSDoc @author.	(fecs-valid-jsdoc)
fecs ERROR → line 55, col 1: Expected file extension `js` or `jsx` or `es` but found `vue`.	(fecs-esnext-ext)

fecs  INFO src/router.js (5 messages)
fecs ERROR → line 11, col 12: Expected `class Home` but found `ArrowFunctionExpression`.	(fecs-prefer-class)
fecs ERROR → line 12, col 14: Expected `class Detail` but found `ArrowFunctionExpression`.	(fecs-prefer-class)
fecs ERROR → line 13, col 16: Expected `class NotFound` but found `ArrowFunctionExpression`.	(fecs-prefer-class)
fecs ERROR → line 14, col 12: Expected `class User` but found `ArrowFunctionExpression`.	(fecs-prefer-class)
fecs ERROR → line 15, col 14: Expected `class Search` but found `ArrowFunctionExpression`.	(fecs-prefer-class)

fecs  INFO src/components/AppBottomNavigator.vue (4 messages)
fecs ERROR → line 28, col 1: Missing JSDoc @file.	(fecs-valid-jsdoc)
fecs ERROR → line 28, col 1: Missing JSDoc @author.	(fecs-valid-jsdoc)
fecs ERROR → line 28, col 1: Expected file extension `js` or `jsx` or `es` but found `vue`.	(fecs-esnext-ext)
fecs  WARN → line 39, col 50: Unexpected block statement surrounding arrow body.	(fecs-arrow-body-style)

fecs  INFO src/components/AppHeader.vue (3 messages)
fecs ERROR → line 47, col 1: Missing JSDoc @file.	(fecs-valid-jsdoc)
fecs ERROR → line 47, col 1: Missing JSDoc @author.	(fecs-valid-jsdoc)
fecs ERROR → line 47, col 1: Expected file extension `js` or `jsx` or `es` but found `vue`.	(fecs-esnext-ext)

**Comment by PengXing** [comment]
`fecs` 更新比较快，那会 `fecs` 的规则还不是这样的，还没有对 vue 文件进行校验，我们会尽快改过来，感谢提醒

**Comment by PengXing** [comment]
追加一下
 `fecs` 对 vue 文件的校验有点问题，首先不说这个 `file` 和 `author` 的问题，文件后缀名这个报错就有点奇怪了

`Expected file extension js or jsx or es but found vue.	(fecs-esnext-ext)`
