### ISSUE TITLE
扩展 Lavas 内置插件 extendWithWebpackChain 无法使用

### ISSUE THREAD

**Issue by maiguangyang** [lavas-project/lavas#171]
// 在 friendly-error 插件创建时扩展自定义参数
    config.plugin('friendly-error').init((Plugin, args) => {
        let customParams = {}; // 扩展传入插件构造函数的参数
        return new Plugin(...args, customParams)
    });

报错，无法使用

**Comment by easonyq** [comment]
你好。请问你是不是根据[这篇文档](https://lavas.baidu.com/guide/v2/advanced/build-config#extendwithwebpackchain)来改动自己的配置文件的？

另外你的报错信息是不是类似

```
ReferenceError: MyPluin is not defined
```

如果是的话，需要把文档中最后一句

```javascript
// 添加第三方插件到指定 Lavas 内置 html 插件之后
config.plugin('my-plugin').after('html').use(MyPlugin);
```

给注释掉，因为 `MyPlugin` 只是文档中一个示意的插件类，直接添加进去并不能直接运行的。

如果你本来就没有写这句话，并且报错也不是我上面列出的，希望你给出更加完整的配置文件和报错信息，帮助我们排查错误，谢谢。
