### ISSUE TITLE
下载 Lavas 模版出错，请检查当前网络

### ISSUE THREAD

**Issue by FEcorlin** [lavas-project/lavas#173]
环境：window 10 ，node v8.9.4，npm v5.6.0
操作步骤：安装好lavas之后，执行lavas init，选择模板类型（1）之后报错。
错误代码：
(node:10420) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 下载 Lavas 模版出错，请检查当前网络
(node:10420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

ps:我在mac上是可以正常初始化lavas项目的。

**Comment by PengXing** [comment]
是不是你电脑上的 Git 访问 Github 有些问题，或者网络不太好？
