### ISSUE TITLE
增加 对 amp  和 mip 的支持

### ISSUE THREAD

**Issue by zuohuadong** [lavas-project/lavas#175]
build 时或者ssr 来实现 amp 和 mip 的支持。
更有利于搜索引擎

**Comment by PengXing** [comment]
这个不行吧，lavas 是基于 Vue 的，Vue 是需要引入单独的 JS 的，AMP 和 MIP 都不允许引入外链 JS，无法支持啊

**Comment by zuohuadong** [comment]
@PengXing  SSR 模式下生成对应页面就行。 CloudFlare 了解下

**Comment by PengXing** [comment]
也不行吧，AMP 要求 CSS 不超过 50k，还有其他诸多限制，不允许直接使用  img 标签，等等，可以看这篇文章 https://css-tricks.com/taking-amp-for-a-spin/#article-header-id-1 和 AMP 官网 https://www.ampproject.org/ ，如果要输出 AMP 和 MIP 合法的 HTML，需要进行非常多的转换，lavas 无法自动实现这些机制

**Comment by zuohuadong** [comment]
@PengXing 感谢回复。
CloudFlare 是基于openresty 在这一层做的转化，当然没那么完美。
从技术角度来说，node webpack 应该也可以实现这个机制。

目前 nuxt 有 AMP 的实现： https://github.com/zeit/next.js/tree/canary/examples/with-amp

可以考虑简化一下
