### ISSUE TITLE
关于windows目录下使用lavas init，下载lavas模板失败解决方案

### ISSUE THREAD

**Issue by lidaoqun** [lavas-project/lavas#179]
### lavas version：2.2.8

windows环境下，lavas init 来初始化第一个项目时，出现了下载lavas模板失败问题，报错如下：

> (node:19364) UnhandledPromiseRejectionWarning: Error: 下载 Lavas 模版出错，请检查当前网络 at 
C:\Users\Mester Lemon\AppData\Roaming\npm\node_modules\lavas\dist\lib\scaffold\template.js:61:19
at Generator.throw (<anonymous>)

导致这个错误的原因是由于git clone 到本地目录时，本地目录出现空格导致下载失败

解决方案就是，template.js  这个文件的 第55行代码 git clone 的targetPath 加上"" 双引号即可（望官方看到能处理下这个bug）。
      修改前源码：yield exec(`git clone ${repo} ${targetPath}`);
      修改后：      yield exec(`git clone ${repo} "${targetPath}"`);

**Comment by yanchifeng** [comment]
我的出现了同样的问题：
lavas 2.2.12

**Comment by yanchifeng** [comment]
lavas 2.2.12
我的出现了同样的问题：
 at C:\Users\Messi\AppData\Local\nvs\node\11.15.0\x64\node_modules\lavas\dist\lib\scaffold\template.js:55:19
    at Generator.throw (<anonymous>)
    at step (C:\Users\Messi\AppData\Local\nvs\node\11.15.0\x64\node_modules\lavas\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\Messi\AppData\Local\nvs\node\11.15.0\x64\node_modules\lavas\node_modules\babel-runtime\helpers\asyncToGenerator.js:30:13
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:4728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
但是没找到所说的代码，应该是node的版本不一致；

**Comment by wangce123** [comment]
lavas 2.2.12
现在的template.js已经改头换面了23333
正在拉取云端数据，请稍候...(node:5968) UnhandledPromiseRejectionWarning: Error: 下载 Lavas 模版出错，请检查当前网络
    at C:\Users\WC\AppData\Roaming\npm\node_modules\lavas\dist\lib\scaffold\template.js:55:19
    at Generator.throw (<anonymous>)
    at step (C:\Users\WC\AppData\Roaming\npm\node_modules\lavas\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\WC\AppData\Roaming\npm\node_modules\lavas\node_modules\babel-runtime\helpers\asyncToGenerator.js:30:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:5968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
