### ISSUE TITLE
如何将静态文件yml打包到dist根目录下

### ISSUE THREAD

**Issue by Juliefuling** [lavas-project/lavas#184]
如何将静态文件yml打包到dist根目录下，看了源码，还是不知道怎么在lavas.config.js中配置

**Comment by PengXing** [comment]
https://lavas.baidu.com/guide/v2/advanced/build-config#ssrcopy

看看这个是否满足你的需求

**Comment by Juliefuling** [comment]
我是这样配置的，但是不起作用

extendWithWebpackChain: (config, {type, env}) => {
        
        let copyList = [{
            from: path.join(__dirname, 'static/nginx.conf'),
            to: path.join(BUILD_PATH, 'nginx.conf')
        }];
        config
          .plugin('copy')
          .tap(options => merge(options, copyList));
    }

**Comment by PengXing** [comment]
以下代码，亲测有效

```javascript
extendWithWebpackChain(config, {type, env}) {
    config.plugin('copy1').use(CopyWebpackPlugin, [[
        {
            from: __dirname + '/lavas.config.js',
            to: __dirname + '/dist/lavas.config.js',
            toType: 'file'
        }
    ]])
}
```

**Comment by Juliefuling** [comment]
我放进来不可以啊，你有引用其他的吗，copy1是你自定义的插件名吗

**Comment by PengXing** [comment]
嗯，随便什么名字，不要把之前的覆盖了就好

**Comment by PengXing** [comment]
你要引入 `CopyWebpackPlugin `

**Comment by Juliefuling** [comment]
这是我的整个配置文件
'use strict';

const path = require('path');
const BUILD_PATH = path.resolve(__dirname, 'dist');
const isDev = process.env.NODE_ENV === 'development';
const isProd = process.env.NODE_ENV === 'production';
const CopyWebpackPlugin = require('copy-webpack-plugin')

module.exports = {
    build: {
        ssr: false,
        path: BUILD_PATH,
        publicPath: '/',
        ssrCopy: isDev ? [] : [
            {
                src: 'server.prod.js'
            },
            {
                src: 'package.json'
            }
        ],
        /**
         * alias for webpack
         *
         * @type {Object.<string, Object>}
         */
        alias: {
            server: {
                'iscroll/build/iscroll-lite$': path.join(__dirname, 'core/iscroll-ssr.js')
            }
        },
        /**
         * node externals
         *
         * @type {Array.<string|RegExp>}
         */
        nodeExternalsWhitelist: [
            /iscroll/
        ]
    },
    router: {
        mode: 'history',
        base: '/',
        pageTransition: {
            type: 'slide',
            transitionClass: 'slide'
        },
        routes:[
           
        ]
    },
    skeleton: {
        routes: [
            {
                path: '/',
                componentPath: 'core/LoginSkeleton.vue'
            },
            {
                path: '/getpass',
                componentPath: 'core/PassSkeleton.vue'
            },   
            {
                path: '/task-list',
                componentPath: 'core/TaskSkeleton.vue'
            },         
            {
                path: '*',
                componentPath: 'core/Skeleton.vue'
            }
        ]
    },
    serviceWorker: {
        swSrc: path.join(__dirname, 'core/service-worker.js'),
        swDest: path.join(BUILD_PATH, 'service-worker.js'),
        // swPath: '/custom_path/', // specify custom serveice worker file's path, default is publicPath
        globDirectory: BUILD_PATH,
        globPatterns: [
            '**/*.{html,js,css,eot,svg,ttf,woff,conf}'
        ],
        globIgnores: [
            'sw-register.js',
            '**/*.map'
        ],
        appshellUrl: '/appshell',
        dontCacheBustUrlsMatching: /\.\w{8}\./
    },
    extendWithWebpackChain: (config, {type, env}) => {
        config.plugin('copy2').use(CopyWebpackPlugin, [[
            {
                from: __dirname + '/lavas.config.js',
                to: __dirname + '/dist/lavas.config.js',
                toType: 'file'
            }
        ]]);
    }
};

**Comment by PengXing** [comment]
`extendWithWebpackChain` 是构建配置，要写在  `build` 里

https://lavas.baidu.com/guide/v2/advanced/build-config 这篇文章一开始就说了
