### ISSUE TITLE
提升首屏渲染速度和加载体验

### ISSUE THREAD

**Issue by zuohuadong** [lavas-project/lavas#190]
之前是用 nuxt ，首次加载的时候只加载当前路由需要的js，然后再加载全局js，减少了首屏渲染时间。

**Comment by PengXing** [comment]
so? 

lavas 也是啊，参考[路由配置项](https://lavas.baidu.com/guide/v2/advanced/router#%E4%BD%BF%E7%94%A8-routes-%E4%BF%AE%E6%94%B9%E8%B7%AF%E7%94%B1%E5%AF%B9%E8%B1%A1) 里的 lazyLoading 配置
