### ISSUE TITLE
如何在后台（比如使用pm2）运行lavas start?

### ISSUE THREAD

**Issue by tangyue0924** [lavas-project/lavas#191]
ssr服务器需要常驻，如何使用pm2来后台管理lavas的运行？谢谢～

**Comment by PengXing** [comment]
看你现在 lavas 是使用的什么模式

1. SPA
  在 SPA 模式下，lavas  start 相当于启动了一个静态文件服务器，这个你可以采用 nginx 代替，只要配置相应的路由即可，路由配置可以参考编译后的 `dist/lavas/routes.json` 文件
2. SSR
  在 SSR 模式下，lavas start 只是运行了 `dist/server.prod.js` 文件，如果想用 PM2 来启动的话，完全可以直接用 PM2 启动 `dist/server.prod.js` 文件，例如可以到 `dist` 目录中运行 `pm2 start server.prod.js -i 0 --name lavas`

两种情况都比较简单，提供了充分的自由度，开发者也可以直接修改 server.prod.js，编写自己的逻辑

**Comment by easonyq** [comment]
没错，lavas 命令行提供的 `lavas start` 多数是供开发调试时使用。正式上线的话，只需要直接配置 nginx 或者运行 node 命令即可，没必要在开发环境上全局安装 lavas 命令行（而且有些线上环境也不允许开发者自行安装全局的命令）
