### ISSUE TITLE
Lavas APP 的路由返回键不正常返回

### ISSUE THREAD

**Issue by 132yse** [lavas-project/lavas#192]
使用 lavas app 打包 apk
发现手机自带的返回按键不能正常返回
app地址：[**戳我**](https://gss0.bdstatic.com/9rkZbzqaKgQUohGko9WTAnF6hhy/assets/pwa/projects/1534841728681/lavas.acgzone.pwa.apk)
然后就是一般前两次后退是正常的，第三次就无法正常后退而是直接退出了
有的时候，三次都没有，是直接退出的

路由的push事件是没有问题的，就是返回按钮不支持路由的事件
但是lavas官方的apk是支持的，所以再考虑是不是对lavas官网的项目做了一些处理

求帮忙，这个比较绝望，今天找了一天的问题，还是没找到::>_<::
但是让我换一个打包工具的话，我还是不乐意的，还是很喜欢 lavas 的呜呜呜
求救

**Comment by 132yse** [comment]
目前已知，魅族是正常的
其他的都不正常::>_<::

**Comment by lixusophie** [comment]
https://lavas.baidu.com/app 现在进不去了
