### ISSUE TITLE
支持vue-bootstrap吗

### ISSUE THREAD

**Issue by tangniyuqi** [lavas-project/lavas#195]
小白 求问

**Comment by easonyq** [comment]
你说的是 [bootstrap-vue](https://bootstrap-vue.js.org/) 吗？

如果是的话，我粗略看了看文档，它的使用方法是

```javascript
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'

Vue.use(BootstrapVue);
```

这样是支持的，你可以把这段放到 `core/app.js` 里面。

**Comment by tangniyuqi** [comment]
谢谢回复 昨晚也已经摸索出来了，不过和vuetify样式有冲突  默认使用的vuetify啊？关联的地方似乎比较多

**Comment by easonyq** [comment]
对，默认使用了 Vuetify。如果你用的是 basic 的模板，把 `core/app.js` 里面的 `Vue.use(Vuetify)` 去掉应该是可以和 Vuetify 脱离关系的。

如果是 appshell 模板，那有点难，因为我记得那个模板的外壳就是用 Vuetify 实现的

**Comment by tangniyuqi** [comment]
嗯 用的appshell 模板
