### ISSUE TITLE
安装有些包提示需要webpack 4.0，因为lavas目前使用的3.x，安装了4.0又提示需要3.x，怎么办？

### ISSUE THREAD

**Issue by zwl1619** [lavas-project/lavas#198]
安装有些包提示需要webpack 4.0，安装了4.0又提示lavas需要3.x，希望lavas可以升级webpack到4.0
![qq 20180902170055](https://user-images.githubusercontent.com/13177997/44954249-c9182200-aed1-11e8-86f8-84b7692220d4.jpg)

**Comment by easonyq** [comment]
目前 lavas 内核使用的是 webpack 3.x 还没有升级到 4.x。这个升级可以列入考虑。

不过在升级之前，还是应该以 webpack 3 为准呀，而且内核代码都是以 3 的格式来写的，你强行安装 4 应该是没用的。
