### ISSUE TITLE
LAVAS ERROR 当前环境下没有检测到 git 命令

### ISSUE THREAD

**Issue by zh918** [lavas-project/lavas#2]
E:\demo>lavas init
LAVAS ERROR 当前环境下没有检测到 git 命令，请确认是否安装 git

E:\demo>lavas -v
LAVAS INFO version:  1.0.7

**Comment by zoumiaojiang** [comment]
由于我们下载以及更新模版是使用 git 工具来实现，使用时是需要系统已经安装了 git 的，所以在使用 lavas 命令行前需要安装 git 。
