### ISSUE TITLE
请问怎么redirect呢

### ISSUE THREAD

**Issue by tangniyuqi** [lavas-project/lavas#201]
比如我想从/page/help跳转到/page/help/faq

下面这样无效：
router: {
        mode: 'history',
        base: '/',
        pageTransition: {
            type: 'fade',
            transitionClass: 'fade'
        },
        routes: [
            {
                pattern: /\/page\/help/,
                redirect: '/page/help/faq'
            }
        ]
}

**Comment by easonyq** [comment]
你那个 pattern，`//page/help/` 不是一个合法的正则吧？正则里 `/` 要加转义符的，试试看 `\/` ？
