### ISSUE TITLE
SPA 下， 脚手架在iOS浏览器不能运行

### ISSUE THREAD

**Issue by FlowerCheng123** [lavas-project/lavas#202]
<img width="435" alt="2018-09-02 10 38 02" src="https://user-images.githubusercontent.com/8719916/44985699-d1e12480-afb3-11e8-8d86-ad900aff8ae4.png">

**Comment by PengXing** [comment]
Vuetify 在 iOS8 下无法运行？

**Comment by easonyq** [comment]
我看了一下，在 AppShell 的模板里面，`store/appShell/appHeader.js` 中有一段：

```javascript
export const mutations = {
    [SET_APP_HEADER](state, appHeader) {
        state = Object.assign(state, appHeader);
    }
};
```

然后我看了下依赖，依赖中的确有 `babel-polyfill`，但可能没有在代码运行之前 `require`。

你先试试看在 `server.dev.js` 和 `server.prod.js` 头上加上 `require('babel-polyfill')` 是否有效？如果OK，我就按你的方案更新模板啦

**Comment by FlowerCheng123** [comment]
我试了一下，还是没用

**Comment by xiaoiver** [comment]
安装一下 object-assign 的 polyfill
```bash
npm install es6-object-assign --save
```

然后可以在 `core/app.js` 中引入
```js
// core/app.js
import 'es6-object-assign/auto';
```
