### ISSUE TITLE
SPA下，inphoneX无法显示状态栏

### ISSUE THREAD

**Issue by zerofront** [lavas-project/lavas#203]
按照教程使用 lavas init 生成的项目，
manifest.json中 设置 "display": "standalone",

在iphone7plus测试可以看到状态栏（时间，电量等）

在iphoneX下，状态栏为全黑，请问有方案解决这个问题吗？

**Comment by PengXing** [comment]
这个现在还没什么好的方法可以解决，不知道设置 banner 的颜色能否解决这个问题
