### ISSUE TITLE
子目录文件命名问题

### ISSUE THREAD

**Issue by zwl1619** [lavas-project/lavas#204]
文档给了下面这样一个示例:
```
detail
    └── _id.vue
```

**问题：**   
如果还有`列表index、增加create、编辑edit`三个组件，那这三个组件命名是不是应该像下面这样？
```
detail
    └── _id.vue
    └── _index.vue
    └── _create.vue
    └── _edit.vue
```

**Comment by easonyq** [comment]
`pages` 下面的都是页面，并不是组件。如果你要开发的是组件，应该去 `components` 目录之类的地方开发，然后在页面中引用。

不过从你问题的描述来看，“列表”，“增加”，“编辑”听上去其实也是页面的意思。如果是页面的话，那放在 `pages` 里面就是 OK 的了。

至于命名，下划线开头是为了动态参数，例如 `detail/_id.vue` 是为了能够命中 `detail/1`, `detail/101` 之类的路由规则，并不是所有的文件名都必须下划线开头，所以那 3 个固定的名字不需要下划线。更多信息你可以查阅[文档](https://lavas.baidu.com/guide/v2/basic/init#lavas-%E8%87%AA%E5%8A%A8%E8%B7%AF%E7%94%B1%E7%94%9F%E6%88%90%E6%96%B9%E6%B3%95)
