### ISSUE TITLE
appShell 版本下 ssr 模式下报错

### ISSUE THREAD

**Issue by FlowerCheng123** [lavas-project/lavas#208]
<img width="849" alt="2018-09-29 10 45 52" src="https://user-images.githubusercontent.com/8719916/46240093-de02ab00-c3d4-11e8-8f02-fbc737e3b94e.png">
一直报找不到lavas/config.json的错  一直转，一直转，
BTW
请问下，我每个页面都需要SEO，用多入口的浏览器渲染好还是使用SSR好？

**Comment by easonyq** [comment]
能否请问一下你的 lavas 版本呢？我这边是正常的，截图如下

### 我的环境

![image](https://user-images.githubusercontent.com/6800839/46590965-016ed980-caea-11e8-9b6b-8f11a039960a.png)

![image](https://user-images.githubusercontent.com/6800839/46590954-db493980-cae9-11e8-9d5e-c0d0b11c9dd3.png)

### 可能的猜测

我看不到你使用了哪个命令。

不过根据你的截图，我猜测你应该是 __在尚未构建 (即 `lavas build`) 过的情况下运行了 `lavas start`__，因为 lavas 只有在生产环境运行时才会寻找 `config.json`。你应该使用 `lavas dev` 来启动调试服务器，或者在执行了 `lavas build` 之后 `cd` 到产出的目录(例如 dist）然后再执行 `lavas start`。

**Comment by PengXing** [comment]
要到 dist 目录中运行 `lavas start`
