### ISSUE TITLE
lavas APP html5 video 标签获取不到部分信息

### ISSUE THREAD

**Issue by 132yse** [lavas-project/lavas#209]
![](http://wx2.sinaimg.cn/mw690/0060lm7Tly1fvtxwudckzj30f00qojsd.jpg)

如图，获取 video.duration 失败
web端是正常的：https://m.chinko.cc/home/100

**Comment by zoumiaojiang** [comment]
属于 lavas app 内核兼容性问题，暂时不好修复，暂时先 close
