### ISSUE TITLE
lavas build之后，precache-manifest文件无法加载

### ISSUE THREAD

**Issue by GlacierXX** [lavas-project/lavas#210]
ssr appshell模板创建项目，build之后lavas start启动项目，precache-manifest文件无法加载，导致返回index.html，从而报错

**Comment by GlacierXX** [comment]
![wechatimg6](https://user-images.githubusercontent.com/7651252/47001788-e5101400-d15d-11e8-9ba7-ec8377a13309.jpeg)
![wechatimg7](https://user-images.githubusercontent.com/7651252/47001802-ea6d5e80-d15d-11e8-9433-28cf03fcff2c.jpeg)

**Comment by easonyq** [comment]
您好。我有几个问题：
1. 你执行 `lavas build` 的时候，有没有警告或者报错？
2. 你执行 `lavas start` 的时候，有没有 `cd dist`？还是直接在根目录就 `lavas start`了？

我这边尝试了 appshell 模板配上 `ssr: true`，生成的 dist 目录是包含 precache-manifest.xxxxx.js 的，你应该是这个文件没生成，才导致了问题。

![image](https://user-images.githubusercontent.com/6800839/47004048-48507500-d163-11e8-956b-b52a76929a32.png)

**Comment by GlacierXX** [comment]
@easonyq
![image](https://user-images.githubusercontent.com/7651252/47004823-f4469000-d164-11e8-85ae-3034491ed6ff.png)
![image](https://user-images.githubusercontent.com/7651252/47004847-04f70600-d165-11e8-825f-e6214aa5f29e.png)

**Comment by GlacierXX** [comment]
@easonyq 
你好
1. lavas build并无报错；
2. build之后进入dist目录，npm install之后lavas start；

**Comment by GlacierXX** [comment]
@easonyq 
![image](https://user-images.githubusercontent.com/7651252/47005047-86e72f00-d165-11e8-81a7-5922e74c7544.png)

**Comment by GlacierXX** [comment]
@easonyq
浏览器source中能看到precache-manifest这个文件，但是请求返回的是index.html 
![image](https://user-images.githubusercontent.com/7651252/47005376-31f7e880-d166-11e8-9ee2-fb02011a9310.png)

**Comment by GlacierXX** [comment]
@easonyq 
1. 按照步骤1执行，注释掉代码之后，依然报错
![image](https://user-images.githubusercontent.com/7651252/47007739-7f2a8900-d16b-11e8-9190-4f1988570f3d.png)
2. 通过地址栏直接访问的结果是错误页面
![image](https://user-images.githubusercontent.com/7651252/47007660-4db1bd80-d16b-11e8-8992-4ca9302e5afc.png)

**Comment by easonyq** [comment]
Service Worker 是会自动安装在浏览器内的，因此每次更新必须先注销掉老的，才会安装新的。你可以在 Chrome Dev Tools 里面找到 Application -> Service Worker 确认是否是最新的

我本地把那句 `registerNavigationRoute` 注释掉并更新后，这个文件是可以访问的哦~

![image](https://user-images.githubusercontent.com/6800839/47058066-f3117380-d1f5-11e8-8e14-ee2279a695dd.png)

**Comment by GlacierXX** [comment]
@easonyq 
我确认了下，service worker是最新的，我也将所有其他的unregister掉了，但是还是不行，这个文件还是访问不到，也点了clear storage
![image](https://user-images.githubusercontent.com/7651252/47060402-09243180-d200-11e8-8fc1-1c780b30e216.png)
换了一个从来没访问过这个项目的FireFox浏览器访问也是报同样的错误
![image](https://user-images.githubusercontent.com/7651252/47060591-d3337d00-d200-11e8-988b-6b563395522f.png)
我对脚手架生成的appShell模板也没有改动过代码

**Comment by GlacierXX** [comment]
@easonyq 
抱歉，并非没有任何改动，根据codelib中的教程，将express服务器换成了koa，我刚用又创建了一个工程默认express是没有问题的，koa使用的版本是2.5.3
![image](https://user-images.githubusercontent.com/7651252/47068333-95455180-d21e-11e8-8ccb-75a629c5a965.png)
![image](https://user-images.githubusercontent.com/7651252/47068367-af7f2f80-d21e-11e8-91c6-7ddad54d60f1.png)

**Comment by easonyq** [comment]
哦，你的意思是说，使用 koa 服务器会有这个问题，express 正常对吧？那我尝试一下。

不好意思给您带来了很多麻烦~

**Comment by easonyq** [comment]
已经修复，请更新 lavas-core-vue@1.2.2 即可解决问题，多谢反馈。

**Comment by GlacierXX** [comment]
@easonyq 好的 多谢
