### ISSUE TITLE
build成功以后不结束

### ISSUE THREAD

**Issue by 48747776** [lavas-project/lavas#215]
`LAVAS INFO 开始构建...
✔ [Lavas build] 读取配置完成
✔ [Lavas build] /Users/leo/git/ThirdPortal000/dist 清理完成
✔ [Lavas build] 路由规则生成完成
✔ [Lavas build] 临时文件写入完成
  [====================] 100% (42.6 seconds)

Build completed in 42.709s

Hash: f7e570e251deca89950f
Version: webpack 3.12.0
Time: 42711ms
                                                Asset       Size  Chunks                    Chunk Names
                                          favicon.ico    4.29 kB          [emitted]
precache-manifest.eba3e6a602a9bfefd6134421ca5aff5e.js    13.9 kB          [emitted]
                                    service-worker.js    1.53 kB          [emitted]`
之后输出了生成的文件list,然后就不继续了.

**Comment by PengXing** [comment]
实际上文件有生成吗？编译完成了吗？

**Comment by 48747776** [comment]
有文件生成,编译应该是完成了,把dist文件夹中的东西手工复制到服务器能正常运行.

**Comment by 48747776** [comment]
` + 5 hidden assets
Child html-webpack-plugin for "index.html":
     1 asset
Child vue-skeleton-webpack-plugin-compiler:
                                                    Asset     Size  Chunks  Chunk Names
    /Users/leo/git/ThirdPortal000/dist/skeleton-index.css  2.65 kB       0
     /Users/leo/git/ThirdPortal000/dist/skeleton-index.js  4.41 kB       0
     + 1 hidden asset
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?{"minimize":true,"sourceMap":true}!node_modules/vue-loader/lib/style-compiler/index.js?{"optionsId":"1","vue":true,"id":"data-v-2113d505","scoped":true,"sourceMap":false}!node_modules/postcss-loader/lib/index.js?{"sourceMap":true}!node_modules/vux-loader/src/style-loader.js!node_modules/vue-loader/lib/selector.js?type=styles&index=0!components/icon/index.vue:
                                      Asset     Size  Chunks  Chunk Names
          static/img/massagist.08a91a85.png  34.7 kB
           static/img/medicine.e45414d2.png  48.9 kB
         static/img/oldNursing.5310b061.png  10.4 kB
    static/img/physiotherapist.99269480.png  45.7 kB
            static/img/waitPay.f81ce9d5.png  11.1 kB
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--10-2!node_modules/postcss-loader/lib/index.js??ref--10-3!node_modules/stylus-loader/index.js??ref--10-4!assets/stylus/main.styl:
                                                Asset     Size  Chunks  Chunk Names
     static/fonts/MaterialIcons-Regular.012cf6a1.woff  57.6 kB
    static/fonts/MaterialIcons-Regular.570eb838.woff2  44.3 kB
      static/fonts/MaterialIcons-Regular.a37b0c01.ttf   128 kB
`

**Comment by PengXing** [comment]
lavas 是 webpack 来编译的，封装在 lavas-core-vue 里面
