### ISSUE TITLE
lavas动态缓存的使用，有么有例子

### ISSUE THREAD

**Issue by lulu52013141516** [lavas-project/lavas#217]
貌似不起作用

**Comment by PengXing** [comment]
能详细一点吗？

**Comment by PengXing** [comment]
https://lavas.baidu.com/guide/v2/advanced/service-worker#%E8%AE%BE%E7%BD%AE%E5%8A%A8%E6%80%81%E7%BC%93%E5%AD%98%E8%A7%84%E5%88%99
