### ISSUE TITLE
关于页面内请求接口问题。盼复。。

### ISSUE THREAD

**Issue by shiliangL** [lavas-project/lavas#219]
如图page/tags/_id.vue 文件中发送的请求路径会带上 http://localhost:3000/tags/api/playlist/detail?id=5001（多带上了 tags字段，前端代理后台配置如下图）

![image](https://user-images.githubusercontent.com/24687496/51086030-4acf6480-177c-11e9-839c-cf59d7c9f5aa.png)

//做了代理
var proxyTable = {
    // proxy table example
    '/api': {
        target: 'http://39.108.65.xxx:3300',
        changeOrigin: true,
        pathRewrite: {
            '^/api': '/'
        },
    }
};

**Comment by PengXing** [comment]
这样看的话，和 proxyTable 没关系吧，前端请求发送出去的时候就带上了 tags，是不是请求 URL 写了相对路径

**Comment by shiliangL** [comment]
带上 proxyTable 是我猜测可能有关的问题，url 书写的时候是没有 tags 的，然后我在 axios 实例的拦截请求里面打印对应的 url 也是没有 tags 的 所以困惑定位不到问题

**Comment by PengXing** [comment]
所以，我上面写了啊，你是不是写了相对路径

**Comment by shiliangL** [comment]
![image](https://user-images.githubusercontent.com/24687496/51253661-ec072680-19d9-11e9-98ec-37b1282e26dc.png)
![image](https://user-images.githubusercontent.com/24687496/51253707-0b05b880-19da-11e9-888a-7e2e6ef4cd60.png)
这样的

**Comment by PengXing** [comment]
你就是写了相对路径，改为 `/api`

**Comment by shiliangL** [comment]
好的 感谢 问题以及处理通过了~
