### ISSUE TITLE
全局事件疑问

### ISSUE THREAD

**Issue by Brania** [lavas-project/lavas#22]
在A页面上通过setAppHeader定义了action，是不是意味着在所有页面都能监听到这个事件？我在某个页面上的操作应该是针对这个页面组件的，为什么要搞成全局事件呢？如果因为壳子没办法，怎么区分不同页面上产生的action动作？

**Comment by Brania** [comment]
重复监听全局事件，监听页面路由后退，再次进入监听页面触发action事件，发现监听代码执行两次，以此类推，执行次数叠加。

**Comment by PengXing** [comment]
你说的是哪个模板呢？

**Comment by PengXing** [comment]
我暂时先关闭这个 issue，你可以后续重新开启它
