### ISSUE TITLE
打开chrome开发者工具，PWA在刷新的时候会切换到installed状态，触发emitUpdate

### ISSUE THREAD

**Issue by asyalas** [lavas-project/lavas#222]
### 现象描述
打开chrome开发者工具，PWA在刷新的时候会切换到installed状态，触发emitUpdate，从而闪现出黑色的刷新tip
不打开无此现象

**Comment by PengXing** [comment]
估计你勾选了 `Update on Reload`，去掉就好

![image](https://user-images.githubusercontent.com/527244/53138104-1c854600-35c0-11e9-989e-c1827253579e.png)
