### ISSUE TITLE
点击header上的回退按钮右侧按钮没有刷新

### ISSUE THREAD

**Issue by Brania** [lavas-project/lavas#23]
不同页面设置了不同的右侧按钮，点击回退到之前一个页面时右侧按钮竟然没有刷新，底部的按钮隐藏和显示偶尔也不受控制。

**Comment by PengXing** [comment]
在每个页面都需要设置 app shell 的 header 和 bottom navigation 的状态，你现在是在哪个模板的哪个页面遇到了这个问题？
