### ISSUE TITLE
version 2.2.1  error:DEFAULT_ENTRY_NAME is not defined

### ISSUE THREAD

**Issue by sally2015** [lavas-project/lavas#27]
windows
node: v8.9.0
npm: 5.5.1
lavas: 2.2.1
看到之前有类似的错误，但是被closed的bug是因为安装了测试版本，但是我的是2.2.1应该是正式版本的吧

**Comment by PengXing** [comment]
你重新创建一个项目试试

```bash
lavas init
```

**Comment by sally2015** [comment]
@PengXing 我忘了说由于公司网络限制不能再cmd中拉取网络数据，所以我是直接下载了lavas-template-vue来启动，但是无论是lavas dev还是npm run dev都是报error:DEFAULT_ENTRY_NAME is not defined错误

**Comment by sally2015** [comment]
@PengXing 不好意思可以关掉了，我认真看了一下原来是没有下载release分支的模板

**Comment by PengXing** [comment]
哦，原来是这样，那我关掉了。
