### ISSUE TITLE
升级到 Workbox@3.x

### ISSUE THREAD

**Issue by xiaoiver** [lavas-project/lavas#31]
目前 Lavas 中使用的是 Workbox@2.1.2，存在以下问题：
1. 开发模式下 service-worker 无法使用，原因是 workbox-webpack-plugin 没有处理开发模式中 webpack 内存文件系统中的静态资源。
2. 生产环境下引入运行时 workbox-sw 的方式不够灵活。对于用户自定义的 service-worker 模版文件，虽然 Workbox 能根据固定的字符串注入 precache 预缓存资源列表，但是引入这个运行时文件的 `importScript` 并不是自动生成的，这就带来了下面的问题：
    - 我们目前在编译流程中将这个文件从 `node_modules` 内拷到 `static/js` 下。当 `publicPath` 发生变动时，用户需要在 `importScript` 处同步手动修改。
    - 当 Workbox 版本升级时，也需要用户手动修改引用路径。所以目前固定了 `2.1.2` 这个版本。

而 Workbox@3.x 开始尝试修复这些问题。API 有一些比较大的改动，比如：
1. 注入 precache 列表不再使用替换固定字符串的方式，而是采用 `importScript` 引用单独的 `precache-manifest` 文件
2. 开发模式下的 service-worker 调试问题，向内存文件系统中正确写入静态资源，我在 SPA 下测试过还是很好用的。
3. workbox-sw 运行时文件拆分成了多个子模块，但这里有一个问题，Google CDN 无法访问的，所以还是得引用本地文件。最近发布的 [3.0.0-alpha-4](https://github.com/GoogleChrome/workbox/tree/v3/packages/workbox-webpack-plugin) 版本解决了这个问题，支持使用本地构建好的版本。

所以目前需要针对 SSR 下的场景进一步测试。

**Comment by yuu2lee4** [comment]
何时升级

**Comment by easonyq** [comment]
我们已经有一个对内测试版本使用了 workbox 3.0。但因为 workbox 3.0 本身也稳定不久，且写法差异较大，我们暂时也还在观察。

你可以查看 `feature-entry` 分支，那个分支用的是 3.0

**Comment by easonyq** [comment]
见 #188
