### ISSUE TITLE
如何正常全局导入module？

### ISSUE THREAD

**Issue by LostNCG** [lavas-project/lavas#32]
如axios, moment 等等， 传统做法是在app.js(入口文件) 直接 import axios from “axios” 即可，
可是在Lavas的框架下， 只能在pages目录下的单页page局部使用， 全局调用会抛出错误 module is not defined

求教， 新转入Node.js 实在documentation 翻遍了都没这方面的说明， 估计是常识所以没有注明吧？

**Comment by PengXing** [comment]
你现在在哪里写的 `import axios from 'axios'`，lavas 导出的项目也有 `core/app.js` 文件，这里也可以引啊

**Comment by LostNCG** [comment]
很抱歉功课太多迟回复了，
我是在lavas 项目下的core/app.js 下引入的
分别尝试了三种不同的引入方式
```js
import Vue from 'vue';
import Meta from 'vue-meta';
// 1. import axios from 'axios';   
// 2. const axios = require("axios");
// 3. Window.axios = axios

import {createRouter} from '@/.lavas/router';
import {createStore} from '@/.lavas/store';
import AppComponent from './App.vue';
Vue.use(Meta);

Vue.config.productionTip = false;

export function createApp() {
   ...
}

if (module.hot) {
    ...
}
```
方式1， 2都抛出了相同的错误 axios is not defined，方法3直接 Window is not defined

![](https://imgur.com/vV72OXG)
![](https://imgur.com/6xrvbh9)

**Comment by PengXing** [comment]
你运行 `npm install --save axios` 了吗？

**Comment by xiaoiver** [comment]
@LostNCG ，错误信息里看你是在 `App.vue` 里使用的 axios，所以你如果只是在 `core/app.js` 里：
```javascript
import axios from 'axios';
```

你需要在 `App.vue` 中引用。另外你不用担心在 `App.vue` `core/app.js` 甚至其他使用到 axios 的地方多次声明的问题，构建工具会处理重复引用依赖的问题的。

至于方法2和1都是一样的，`import` 会被 Webpack 通过 `babel-loader` 和插件转成 `require` 的。
方法三的问题是在 SSR 模式也就是 Node 环境下，`window`，`document` 这些浏览器环境特有的变量是都不存在的。

**Comment by LostNCG** [comment]
@PengXing 是的， 确认。

@xiaoiver 原来如此，正是因为担心多次声明会导致重复依赖的问题， 才想全局导入模块， 既然构建工具会自行处理那就没问题了， 感谢你的回复
