### ISSUE TITLE
项目建成后，运行没有报错，但也没有出现相关的信息，运行不了

### ISSUE THREAD

**Issue by leson1986** [lavas-project/lavas#33]
如题：
lavas dev后，出现：
在终端上运行：
LAVAS INFO Launching Lavas debug server ...

 在GIT BASE运行：
$ lavas dev
LAVAS INFO 正在启动 Lavas 调试服务器...

试过重启电脑，重启编辑器（VSCODE），安装了两个模板，都一样的效果。

**Comment by easonyq** [comment]
我们今天发布新功能（自定义配置文件 #35 ）
在更新模板的时候但还没发布模板时您正好初始化了项目，导致了这个问题。

您可以检查一下，lavas 目前版本2.2.3，初始化出来的项目中可以观察 server.dev.js 中，如果不存在 `module.exports = options => {xxxx}` 则为正确。

如果还无法启动，请告诉我，我重新打开这个 issue，多谢~
