### ISSUE TITLE
Windows10上lavas init运行不了

### ISSUE THREAD

**Issue by liminjun** [lavas-project/lavas#4]
通过`npm install -g lavas`成功安装了lavas了，但是运行`lavas init`。控制台报错如下：

![image](https://user-images.githubusercontent.com/966009/27939002-7857afb8-62f4-11e7-836b-2e5098e89f21.png)

操作系统和架构
Windows10 专业版。64位

**Comment by PengXing** [comment]
这个问题应该是 npm 本身的问题，是不是 npm 的 bin 目录没有添加到环境变量的 Path 中
