### ISSUE TITLE
core/index.html.tmpl 功能强化

### ISSUE THREAD

**Issue by easonyq** [lavas-project/lavas#40]
目前的 index.html.tmpl 可以使用 baseUrl, renderEntry, renderMeta 等方法进行模板的编写，可以适应常规需求。

但如果开发者有自定义的变量想要挂载并使用，因为lavas-core黑盒的关系尚不支持。

可以考虑将模板变量开放，开发者自定义挂载的对象并自由使用。

**Comment by easonyq** [comment]
SSR 情况下，开发者通过在 entry-server.js 中把需要使用的对象挂载到 context 中，可以实现在模板 index.html.tmpl 中使用这个对象。
另外， #29 中提到的改动，允许模板恢复使用 inject: true，因此 renderScript, renderState 等都去掉了。

不过 SPA 的情况下还无法实现，从原理上讲，SPA 由前端渲染，在后端 webpack 编译 html 的时候并不会执行 entry-client.js，所以无法获取其中的某个开发者挂载的变量，也就无法替换了。

**Comment by PengXing** [comment]
追加一个问题

**是否需要将 SPA 和 SSR 两种情况下的模板合并为一个文件**

说一下我的考虑

1. 现在的融合方式比较别扭，虽然合并为一个文件，但是基本内容还是分为两块
2. 用户是否有频繁切换 SPA/SSR 的需求
3. 拆分为两个文件和合并为一个文件，哪种方式教学成本更低

**Comment by easonyq** [comment]
我的理解，分拆成两个文件的优势有：
1. 更加清晰，各司其职，不用在一个文件里找 if/else
劣势
1. 开发者只用一种模式开发，另一种的模板文件就是浪费，而且大多数情况下开发者不会/不敢删
2. core目录又多一个文件

**Comment by PengXing** [comment]
我还是觉得分开好，ssr.html.tmpl 和 spa.html.tmpl

可以来投个票，我投分开

**Comment by easonyq** [comment]
经过修改，现在同时支持两种模式。

1. 开发者存在 `core/spa.html.tmpl` 或者 `core/ssr.html.tmpl` 时，优先使用此二者之一（视具体渲染模式而定）
2. 如果没有此二者，则使用 `core/index.html.tmpl` 当做模板。

同时，`index.html.tmpl` 也支持两种语法，分别是包含 `if (ssr)` 的较新的版本，和包含 `renderMeta` 的较老的版本。
我会尽快更新文档以说明这个改动。
