### ISSUE TITLE
有关icons的管理

### ISSUE THREAD

**Issue by leson1986** [lavas-project/lavas#41]
官方：<v-icon>room</v-icon>
请问，在哪里可以看得到官方提供的所有font-icon?
如果新增又需要注意什么才不会影响官方提供的，并且使用方式跟官方的一致？

**Comment by leson1986** [comment]
已经找到material

**Comment by xiaoiver** [comment]
后续可能考虑增加自定义 svg 引入的方式。
类似之前的 svg-loader，不一定会内置，但可以以 Codelab 形式介绍。

**Comment by leson1986** [comment]
期待可以自定义版本的

**Comment by xiaoiver** [comment]
@leson1986 ，我增加了一个 [Codelab](https://lavas.baidu.com/codelab/svg-loader/)，可以参考教程中的步骤添加一个简单的 svg-loader，目前支持两种 SVG 的使用方式：
1. Font Awesome 图标
2. 第三方 SVG 图标，目前仅支持多个 `<path>` 的，包含复杂样式和结构（例如 `<def>`）的 SVG 还不支持
