### ISSUE TITLE
打包之后的事儿

### ISSUE THREAD

**Issue by leson1986** [lavas-project/lavas#42]
请问，打包之后，按照官方提示的，还要跑npm install和lavas start命令，是不是需要在服务器上配置node环境？也就是说并不像普通的SPA项目一样，打包完，直接扔上服务器，就可以直接运行？

**Comment by PengXing** [comment]
如果你选择的是 SSR，那是这样的，如果选择的是 SPA，就打完包往服务器上扔就行了
[切换 SSR 和 SPA](https://lavas.baidu.com/guide/v2/advanced/build-config#ssr)
