### ISSUE TITLE
ssr 无限循环

### ISSUE THREAD

**Issue by PengXing** [lavas-project/lavas#43]
复现步骤：

1. `lavas init` 选择 `AppShell` 模板，ssr 默认为 true
2. 安装 less 的依赖库 `cnpm install --save-dev less-loader less`
3. 修改 core/App.vue 文件，增加一段 less 文件，如下
4. 等待编译完成，删除这段 less 样式，就会出现无限循环

```html
<style lang="less">
body {
    background-color: red;
}
</style>
```

**Comment by xiaoiver** [comment]
这里其实有两个问题：

## 循环刷新的问题

无限循环的问题应该是开发模式下文件名包含类似 `[hash]` 造成的，
相关 [ISSUE](https://github.com/webpack/webpack/issues/1914#issuecomment-174171709)。里面 Webpack 作者提到不建议在开发模式下使用。应该是内存文件系统的问题，多次触发了 Webpack HMR 刷新。

看代码的时候发现 Nuxt 也有[类似的处理](https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/builder.js#L207-L217)，特意去除了所有 `[hash]` `[chunkhash]` 和分离样式的 `contenthash`。

但是我记得 Vue 官方模版里开发模式下也是这么写的，所以要搞清楚原因可能还得看看 webpack watch 的代码。

## App.vue 的 HMR 问题

修改 App.vue 这样的根组件，HMR 会显示这样的信息
> [HMR] Root or manually mounted instance modified. Full reload required.
此时需要手动刷新页面。

查到了 vueify（帮助 browserify 转译 .vue 文件，类似 webpack 中的 vue-loader） 的一个 [ISSUE](https://github.com/vuejs/vueify/issues/25#issuecomment-155914797)。里面 Vue 作者解释了一下原因并给出了 vueify 中针对这个问题的 hack 方式，但是链接失效了，所以要实现这个功能还得看看现在的 vueify 代码。

另一个可能的做法是我们手动 watch App.vue，通过 websocket 连接向浏览器发送刷新指令，这样开发者就不用手动刷新了。这个还需要验证下。

**Comment by PengXing** [comment]
ok，那我们是否可以先采取 nuxt 的方案一样在开发模式下将 hash 等会导致 webpack watch 出现问题的配置去掉来解决这个问题。

**Comment by xiaoiver** [comment]
可以安装 lavas-core-vue@1.0.4-rc.1 这个版本测试

**Comment by PengXing** [comment]
验证已修复
