### ISSUE TITLE
每个路由组件拥有独立的 Skeleton？

### ISSUE THREAD

**Issue by xiaoiver** [lavas-project/lavas#44]
## 问题描述

目前 Skeleton 是在构建时使用 Vue SSR 把样式和 DOM 内联到 HTML 中，最大程度减少白屏时间。
但如果 SPA 里各个路由页面差异很大，很难抽象出统一的一个“页面骨架”，这种场景下常常退化成了 Loading。

饿了么是在 **MPA** 下采用这种方案，所以效果很好。商家列表页，菜品详情页都是独立页面，因此可以有独立的 Skeleton，我们在 MPA 方案中也提供了多 Skeleton 配置。但如果我们想提升在 SPA 中的效果，需要额外做一些改动。

## 可能的解决方案

核心问题其实是 Skeleton 在 MPA 场景下与页面入口一一对应，而在 SPA 中需要和路由组件一一对应。

理想状态下，每个路由组件可以有各自独立的 Skeleton，也就是页面的初始状态。
这就要求在构建时把所有 Skeleton 的样式和 DOM 都内联到 HTML 中，同时增加基于当前路由的逻辑判断，隐藏展示正确的 Skeleton 内容。

```html
<style>全部 Skeleton 样式</style>
<div id="page1" style="display:none">Page1 Skeleton</div>
<div id="page2" style="display:none">Page2 Skeleton</div>
<script>
// hash history 模式？
if (getMatchedRoute(window.location.href) === '/page1') {
// 展示 page1
}
else {
// 展示 page2
}
</script>
```

是否需要在 vue-router 加载完毕之后？这样白屏时间会增加。

**Comment by PengXing** [comment]
根据路由判断当前应该展示的 Skeleton 和 Vue 的逻辑本身并没有直接的关系，所以，不需要在 vue-router 加载之后，应当在页面运行到判断当前页面的逻辑的地方就展示路由对应的 Skeleton

**Comment by xiaoiver** [comment]
> 根据路由判断当前应该展示的 Skeleton 和 Vue 的逻辑本身并没有直接的关系，所以，不需要在 vue-router 加载之后，应当在页面运行到判断当前页面的逻辑的地方就展示路由对应的 Skeleton

是的，根据路由模式 history/hash 判断当前展示哪个 Skeleton 这个逻辑比较简单。

所以难点可能在于，由于 SPA 中 Skeleton 和路由路径对应，相应的配置也得基于路由。
单独使用 vue-skeleton-webpack-plugin 时，需要通过配置指明两者的对应关系：
```javascript
{
    '/page1': path.join('@/components/Page1Skeleton.vue')
}
```

而使用 Lavas 时，可以按照某种特殊的命名约定，便于构建时查找，例如 `/pages` 下：
`Page1.vue` 对应的 Skeleton 是 `Page1Skeleton.vue`

**Comment by xiaoiver** [comment]
vue-skeleton-webpack-plugin@1.1.9 版本已经支持。
在 Lavas SPA 模式下使用时，只需要在 `lavas.config.js` 中新增配置项 `skeleton`：
```javascript
skeleton: {
    enable: true, // 可关闭整个 skeleton 特性
    routes: [
        {
            path: '/test', // 路由路径
            skeletonId: 'xxxxx', // DOM 元素 id，可指定，未指定时自动生成，例如 `test-skeleton`
            componentPath: 'core/TestSkeleton.vue' // Skeleton 组件路径
        },
        {
            path: '/test2',
            componentPath: 'core/TestSkeleton2.vue'
        },
        {
            path: '*',
            componentPath: 'core/Skeleton.vue'
        }
    ]
}
```

这样访问不同路由将展示对应的 Skeleton。
