### ISSUE TITLE
Vueconf大会中yyx提到vue-cli 3.0将PWA by default，所以lavas还有存在的必要么？

### ISSUE THREAD

**Issue by regrex** [lavas-project/lavas#5]
RT

**Comment by PengXing** [comment]
首先，对 vue 的这个做法，我们很赞同，大家都是为了能让 web 的体验更好。
然后，我们说到存在的必要这个问题上，lavas 解决的问题和 vue 的 PWA 模板解决的问题不完全相同，比如下面几个问题，vue 提供的 PWA 模板并没有解决。

- 页面前进后退动画
- service worker 更新，及更新后的提示
- App Shell
- App Skeleton

vue 官方并不会对这些问题的解决方法直接导出给开发者，需要开发者查阅文档写代码解决，而 lavas 希望的是开发者一般情况下不需要关心这些问题，我们帮开发者直接解决这些问题。

出发点不一样，所以并不冲突，lavas 是一个更激进一点的解决方案。

欢迎继续提问。

**Comment by yanni4night** [comment]
![我的天哪](https://ws3.sinaimg.cn/large/006tNc79ly1fhewp7i77hj30bl0bw751.jpg)
