### ISSUE TITLE
ReferenceError: renderMeta is not defined

### ISSUE THREAD

**Issue by easonyq** [lavas-project/lavas#52]
lavas build

<img width="836" alt="cfde46bec02bb82c131e97dc0e7ed5fe" src="https://user-images.githubusercontent.com/6800839/35078663-3e8841ce-fc3e-11e7-9ac3-ba111978185e.PNG">

**Comment by easonyq** [comment]
和 #47 类似，都是由于多个模块之间版本不匹配所致。

#47 是由于 lavas 和 lavas-template 之间的不匹配；这里是由于 lavas-template 和 lavas-core-vue 之间的不匹配

核心原因在于对 core/index.html.tmpl 的修改（#40）

Lavas 对类似的的版本问题已经引起重视，以后的版本发布将只局限在 __每周四__，并且对老版本均进行兼容。

**Comment by PengXing** [comment]
临时解决方法

1. 重新运行 `lavas init` 创建一个新项目
2. 重新安装 `lavas-core-vue`，将版本固定在 1.0.3 以下，比如 `npm i lavas-core-vue@1.0.2`

**Comment by easonyq** [comment]
还有个比较快速的方案，把 lavas init 新创建的项目中 `core/index.html.tmpl` 复制到现有的项目中，即可避开 renderMeta 的错误。

**Comment by easonyq** [comment]
lavas-core-vue 1.0.4 版本已经发布，开发者可以更新了。
