### ISSUE TITLE
manifest.json 路径可配

### ISSUE THREAD

**Issue by PengXing** [lavas-project/lavas#56]
当前 lavas.config.js 不可配置 manifest.json 文件地址，虽然可以在模板中写死 manifest.json 的路径，但是这种情况下会导致 manifest.json 的 URL 不会添加版本信息，导致这个文件不会更新

最好的解决方案应该是 lavas.config.js 增加一个配置 manifestUrl: '/static/manifest.json'，编译阶段自动加上 `?v={{ BUILD_TIME }}`

**Comment by easonyq** [comment]
### 当前版本
`core/index.html.tmpl` 经过一次升级 （把 client/server 两种模板合到一起后），所有标签都暴露给开发者，因此非常直观。观察升级后 `lavas init` 的初始化项目，可以发现：

```
<!-- ssr -->
<link rel="manifest" href="{{ config.build.publicPath }}static/manifest.json?v={{ config.buildVersion }}">

<!-- spa -->
<link rel="manifest" href="<<= htmlWebpackPlugin.options.config.build.publicPath >>static/manifest.json?v=<<= htmlWebpackPlugin.options.config.buildVersion >>">
```

因此默认情况下，已经会把构建信息当做 `v` 参数添加到后面，以解决缓存的问题，达到你提的效果。
至于 url 本身，因为 `index.html.tmpl` 也是完全开放给开发者的模板文件，在这里写更加直观，我认为就没必要再加一个配置项，然后 lavas core 再读取配置项写入到模板中。

### 老版本
对于老版本的 `index.html.tmpl` （即不区分 ssr/spa，而是使用类似 `<%= renderMeta() %>` 的语法），也会自动加上取值为 `buildVersion` 的 `v` 参数，所以效果和新版本是一致的。
**唯一的问题是**，manifest url (`/static/manifest.json`) 是固定的，无法由开发者调整，即约定的。但考虑到我们不再建议开发者使用老版，所以我想这样应该也不是不能接受吧。
