### ISSUE TITLE
Error 500 service worker response error

### ISSUE THREAD

**Issue by summerinsect** [lavas-project/lavas#59]
在某些手机里连续刷新几次之后，会报错卡死在Skeleton页面，再打开还是卡死状态，要清除缓存才能恢复。

手机品牌：oppo R9s
android版本：6.0.1
web内核：Chrome/63.0.3239.83
报错：Failed to load resource: the server responded with a status of 500 (Service Worker Response Error) 

![service_worker](https://user-images.githubusercontent.com/6075540/35144908-ee86aebe-fd40-11e7-8751-c631d254b1b9.png)

**Comment by PengXing** [comment]
这个问题是偶现还是必现呢？现在静态资源采用的是什么服务器响应的？

**Comment by summerinsect** [comment]
@easonyq 
不太清除router的base是在哪里设置的。
assetsPublicPath 倒是设置过，是/wbf-base/
如果修复了，是不是我这边要update lavas？

@PengXing 
在这个机型上刷新几次是必现的，采用的是nginx

**Comment by summerinsect** [comment]
把服务端改成http就没问题了，https就会有这个问题。

**Comment by PengXing** [comment]
我用 R9s Chrome 试过了，用 https://wobaifu.10010.com/wbf-base/ 这个链接，没复现

有什么比较稳定的方法可以复现这个错误吗？

**Comment by easonyq** [comment]
router 的 base 在 `lavas.config.js` 中 `router` 段，一般如下：
```javascript
router: {
    mode: 'history',
    base: '/',
    pageTransition: {
        type: 'fade',
        transitionClass: 'fade'
    }
},
```
这里的 base 就是 vue-router 的 base，表示 URL 的公共前缀。
你可以参考我关联的那个 issue ，看看编译生成的 service-worker.js 中，上方的静态文件列表的文件名和最后 `registerNavigationRoute` 的参数是否不一致。如果不一致则和那个 issue 一样，否则就是别的问题吧。

**Comment by summerinsect** [comment]
@easonyq 
好的，谢谢

@PengXing 
网页不能复现，是在app里打开出现的问题。
后端人员在配合我找问题，可能不是lavas这边的问题。
找到问题我再来回复吧，感谢。
暂时把刷新页面，改成刷新接口，能治标。

**Comment by PengXing** [comment]
好的，那我先把 issue 关掉了，后续找到问题辛苦再把 ISSUE 打开，谢谢
