### ISSUE TITLE
支持 proxyTable

### ISSUE THREAD

**Issue by PengXing** [lavas-project/lavas#60]
很多开发者没有 Node 开发经验，也不了解 lavas，不知道 server.dev.js 或者 server.prod.js 能够自己修改并且增加类似于 webpack proxyTable 的功能

如果 lavas 能够默认支持就好了

**Comment by xiaoiver** [comment]
可以在开发模式内置这个功能，或者以 Codelab 形式给予指导。

**Comment by PengXing** [comment]
在 `lavas-template-vue` 中支持，移步 https://github.com/lavas-project/lavas-template-vue/issues/18
