### ISSUE TITLE
使用了 defines 后，仍然得不到变量

### ISSUE THREAD

**Issue by zgj1024** [lavas-project/lavas#62]
参考 [这里](https://lavas.baidu.com/guide/v2/advanced/build-config#defines)的做法
 在`lavas.config.js`中定义了
```
const isDev = process.env.NODE_ENV === 'development';
const isProd = process.env.NODE_ENV === 'production';


defines: {
    base: {
        BASE_URL: isDev
            ? JSON.stringify('http://192.168.0.233:5555/')
            : JSON.stringify('http://192.168.0.233:5566/')
    }
}

```

但是在 `server.dev.js` 中使用的时候是 undefine
```
console.log("BASE_URL:"+ BASE_URL)

const proxyTable = {
    '/public': {
        target: BASE_URL,
        changeOrigin: true
    }
};
```

**Comment by xiaoiver** [comment]
defines 使用的是 Webpack [DefinePlugin](https://doc.webpack-china.org/plugins/define-plugin/)，其中定义的变量只有在 Webpack 编译时才能访问。而 server.dev.js 只是开发服务器脚本，并不会参与 Webpack 编译，所以也就访问不到这些变量了。

**Comment by zgj1024** [comment]
@xiaoiver 明白了，谢谢
