### ISSUE TITLE
在asyncData请求数据，页面没刷新

### ISSUE THREAD

**Issue by leson1986** [lavas-project/lavas#72]
![image](https://user-images.githubusercontent.com/3852354/35852837-e48fc934-0b66-11e8-8f39-20b4475d9576.png)
此处的后台成功打印出请求的数据
![image](https://user-images.githubusercontent.com/3852354/35852884-ffbbcb68-0b66-11e8-8f3f-966d1f2b700d.png)
lists数组依然为空
![image](https://user-images.githubusercontent.com/3852354/35852946-34ed7e26-0b67-11e8-915f-0e0840991b8c.png)

具体如上图，请问是我哪个步骤出错了？

**Comment by PengXing** [comment]
asyncData 是无法访问 this 的，看下面这个链接的 **带有逻辑配置的组件(Logic Collocation with Components)** 章节里有写，如果有设置数据的需求，可以利用 store 来存取数据

https://ssr.vuejs.org/zh/data.html

**Comment by leson1986** [comment]
**官方教程存在误导还是我才疏学浅？**
以下摘自官网：为了支持服务端渲染 (SSR) ，每个页面组件都应当能够在服务端和浏览器端正常渲染。 Lavas 给开发者暴露了 async asyncData() 方法，开发者一般通过实现这个方法来完成一些渲染前的操作，例如发送请求、获取数据和简单计算等，并且这些操作是同时支持服务端和浏览器端的。在本节中，我们就在 asyncData 方法内实现发送请求获取数据。


![image](https://user-images.githubusercontent.com/3852354/35893452-11398a6a-0be9-11e8-99a2-c82b4e55ce01.png)
@PengXing

**Comment by PengXing** [comment]
Codelab 的 [发送请求](https://lavas.baidu.com/codelab/get-started/request) 章节的例子里没有使用 `this`，描述也没啥问题，不知道是哪里理解有偏差。。？

**Comment by leson1986** [comment]
描述里写明可以在asyncData（）方法中请求，获取数据，如果不能使用于渲染后的DOM当中，应该说明，而不是很笼统的说一通。虽然例子里没有使用this，但，例子里确是使用axios请求数据，这就有误导作用了，至少对于我这个比较笨的人来说，是起到误导了。
抱歉，我也只是想能更清淅的看得懂官方文档而已。或者你说的是对的，官网是没问题，只是我的理解有偏差

**Comment by easonyq** [comment]
@leson1986 你好！感谢对lavas的反馈！
`asyncData` 方法的作用确实是发送请求，获取数据。在获取数据后，一般情况会设置到 store 里面，再通过 `mapState` 等方法给页面使用，这是一套常用的流程，在 Codelab 中也有描述，相信你也看到了。
你提到的误解主要原因在于，Codelab 的步骤中，这里是先介绍 axios 发送请求，再引入 store 进行管理，__两章分离开来导致了这个例子只用 axios 而不用 store __。我的例子中的确没有涉及 this，但也没有详细指明不能使用 this，这一点我会去更新文档以避免再次引发误解。
最后还是感谢您的关注和反馈~希望以后我们一起多多学习研究 lavas, vue 和 pwa。
