### ISSUE TITLE
SPA 中进一步减少白屏时间

### ISSUE THREAD

**Issue by xiaoiver** [lavas-project/lavas#73]
## 问题描述

在开启 [Skeleton 特性](https://lavas.baidu.com/guide/v2/advanced/appshell#spa-%E6%A8%A1%E5%BC%8F%E4%B8%8B%E7%9A%84-skeleton)的情况下，SPA 渲染时间线如下：

![](https://boscdn.baidu.com/assets/lavas/codelab/skeleton.png)

可以看出尽管已经将 Skeleton 所需的样式内联到了 HTML 中，HTML 解析完成后并不能立即开始渲染 Skeleton，必须得等到样式表（index.css）加载之后。

同样使用 Skeleton 的 eleme 也是如此：
![](https://boscdn.baidu.com/assets/lavas/codelab/eleme-skeleton.png)

样式表阻塞渲染在大部分场景下都是合理的，但是既然使用了 Skeleton，这样做就显得多余了。而且如果样式表体积很大，白屏时间将大大增加，Skeleton 并没有发挥理想中的作用。

### 关闭样式分离
在开发模式下，关闭了分离样式功能，效果十分理想。由于没有了样式表的阻塞，HTML 解析之后立即展现 Skeleton，样式由 JS 加载之后插入 HTML：
![](https://boscdn.baidu.com/assets/lavas/codelab/dev-skeleton.png)

但如果在生产环境也关闭这个特性，可能会带来缓存方面的问题，而且 JS 文件不可避免体积增大。
但是好处是由于内容由 JS 渲染，样式也由 JS 插入，因此并不会出现 FOUC 内容闪烁现象。

### 非阻塞样式表

如果能让样式表不阻塞渲染就好了，可以尝试下面的方法：
[Loading CSS without blocking render](https://keithclark.co.uk/articles/loading-css-without-blocking-render/)

但是如果采用这个方法，如果 JS 加载完毕开始渲染内容，而此时样式表还没有下载完成，就会出现 FOUC。

**Comment by xiaoiver** [comment]
https://github.com/filamentgroup/loadCSS

**Comment by PengXing** [comment]
这样有一定的概率会导致闪屏，如果 JS 先加载完并且执行完成，样式再出来

将样式和 JS 的外链按顺序都放在 `<div id="app">skeleton style and html</div>` 后面，`head` 标签里写 preload 的标签，是不是就能解决 Skeleton 优先渲染的问题

**Comment by xiaoiver** [comment]
我们尝试了以下两种方法：

## 把 `<link>` 放到 `<body>` 中

希望把 `<link>` 放到 Skeleton DOM 之后，不阻塞 HTML 渲染。

但是 Chrome 和 FF 下表现不一致：
[Chrome 问题描述](https://bugs.chromium.org/p/chromium/issues/detail?id=481122)
[Chrome 中的测试结果](http://www.webpagetest.org/video/compare.php?tests=150424_57_12PJ-r%3A1-c%3A0&thumbSize=200&ival=100&end=visual)
[FF 中的测试结果](http://www.webpagetest.org/video/compare.php?tests=150424_MS_1297-r:1-c:0)

可见 FF 中是理想中的效果，而 Chrome 不行。所以这种方式无法解决这个问题。

## 异步加载 CSS
上面提到的修改 `rel` 方法，或者使用 XHR 请求样式表，本质都是一样。但是如果样式表很大，由于不再阻塞 HTML 渲染，在加载完之前一旦 JS 执行，就会出现 FOUC。

所以需要在异步请求的基础上，配合 JS 轮询样式是否已经加载完毕：
```html
<link rel="preload" href="path/to/mystylesheet.css" as="style" onload="this.onload=null;this.rel='stylesheet';window.STYLE_READY=1;">
```

在 entry-client 中，轮询成功后再渲染到挂载点上：
```javascript
await checkStyleReady();
app.$mount();
```

**Comment by PengXing** [comment]
事件或者回调函数会比轮询要好一些，这里得判断是不是 `!isServer`

**Comment by xiaoiver** [comment]
效果如下，可以看出使用非阻塞样式表之后，Skeleton 展现大大提前：
![image](https://user-images.githubusercontent.com/3608471/36834922-6e99d466-1d6f-11e8-8364-b73bc7a9dbb5.png)

**Comment by xiaoiver** [comment]
必须等到发布 lavas-core-vue@1.0.8 之后，再修改 lavas-template 中 entry-client.js 的内容。

**Comment by xiaoiver** [comment]
这个特性只会在满足以下条件下开启：

**Comment by Kiiiwiii** [comment]
preload 方式异步加载 css，为何在 head 中，再正常加载一个 stylesheet，该方式就失效了。
单独使用 preload
```  
<head>
<link rel="preload" href="static/a.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript>
    <link rel="stylesheet" href="static/a.css">
  </noscript>
</head>
```

结果：
![screen shot 2018-09-23 at 7 32 35 pm](https://user-images.githubusercontent.com/22943323/45931000-b12f3d80-bf67-11e8-84fb-0c29ca22f2d7.png)

**Comment by Kiiiwiii** [comment]
两个 style sheet 在 head
```
<head>
  <link rel="preload" href="static/a.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript>
    <link rel="stylesheet" href="static/a.css">
  </noscript>

  <link rel="stylesheet" href="static/b.css" >
</head>
```

结果
![screen shot 2018-09-23 at 7 36 32 pm](https://user-images.githubusercontent.com/22943323/45931041-21d65a00-bf68-11e8-9411-a85faef3c60a.png)
