### ISSUE TITLE
每次刷新的时候样式都会比较晚加载出来

### ISSUE THREAD

**Issue by coder30** [lavas-project/lavas#79]
如图![image](https://user-images.githubusercontent.com/22569249/36082199-2b0dbfa4-0fe2-11e8-8e55-b3d9c4f7dd80.png)
感觉看起来很奇怪

**Comment by xiaoiver** [comment]
@coder30 ，在**开发模式**下，默认禁用了样式分离，所以样式内容是由 JS 异步插入文档中的，所以你会看到缺少样式的内容闪烁现象(FOUC)。禁用后，在开发模式下能够提升 rebuild 速度。

而在**生产环境**构建中，默认开启了这一特性，通过[extract-text-webpack-plugin](https://doc.webpack-china.org/plugins/extract-text-webpack-plugin)，将 CSS 从 JS 中分离出来，这样就会阻塞 HTML 的渲染，也就不会出现 FOUC 了。

所以如果你想在**开发模式**也开启这一特性，可以在 `lavas.config.js` 中配置：
```javascript
// lavas.config.js
build: {
    cssExtract: true,
}
```

**Comment by coder30** [comment]
@xiaoiver 太棒了，问题解决了，非常感谢你的解答
