### ISSUE TITLE
npm run dev problem

### ISSUE THREAD

**Issue by zytx121** [lavas-project/lavas#8]
after `npm install` ，the`npm run dev` have some problem.

![image](https://user-images.githubusercontent.com/10410257/28508914-cd7fda86-7070-11e7-9147-c56ef478864c.png)

**Comment by zytx121** [comment]
i delete the key in the slot , then work . but i don't know if have side effects ?

**Comment by zoumiaojiang** [comment]
it's a  bug in early [commit](https://github.com/lavas-project/lavas-template-vue-appshell/commit/c19d1d6a2d70082bca0bbc37012b4e9db868c788), thanks for your remind, it's fixed now

**Comment by zytx121** [comment]
![image](https://user-images.githubusercontent.com/10410257/28509586-e1e6a96e-7075-11e7-9d05-31dffbbd4bfd.png)
i mean...  your commit cause a bug . the green line doesn't work in my conputer, but old code does work.
