### ISSUE TITLE
什么时候支持typescript？

### ISSUE THREAD

**Issue by aojianwu** [lavas-project/lavas#80]
如题

**Comment by xiaoiver** [comment]
近期会参考 [TS模板](https://github.com/Microsoft/TypeScript-Vue-Starter) 修改部分代码，下个版本会支持。

**Comment by zuohuadong** [comment]
个人感觉，vue 项目只需要对 ts提供基本支持即可。
真要喜欢 ts ，何不尝试 angular ？

**Comment by jswh** [comment]
有意参与ts的支持工作，但是没有看到如何contribute的说明？

**Comment by PengXing** [comment]
我想知道这里说支持 ts，是啥意思？是指 lavas init 下来的模板都是 ts 吗？这个应该可以通过改 webpack 的配置来做到吧？

**Comment by jswh** [comment]
嗯，就是init的模板是ts。我试着改过，但是有些文件是在.lavas 文件夹下，还有一些.d.ts的定义文件需要增加，每个项目独立修改挺麻烦的。

**Comment by PengXing** [comment]
嗯，我明白了，如果需要改成 ts，需要修改的部分包括

- basic 和 appshell 模板
- lavas-core 生成 ts 模板
- lavas-core 的 webpack 配置增加 ts 相关 loader
