### ISSUE TITLE
有带底部导航栏的lavas2.0的模板吗

### ISSUE THREAD

**Issue by coder30** [lavas-project/lavas#81]
我之前用1.0版本的时候是有带底部导航栏的，2.0有带底部导航栏的模板吗

**Comment by PengXing** [comment]
不好意思，这个去掉了，不过添加也很方便，在 vuetify 找到 BottomNavigation 组件，修改 `core/App.vue` 文件，添加即可，也可以参照 [lavas1 的 App Shell 模板](https://github.com/lavas-project/lavas-template-vue-appshell)
