### ISSUE TITLE
[bug report]SPA 应用中HTTPS下静态文件带了参数不能访问，不带就可以

### ISSUE THREAD

**Issue by jamninetyfive** [lavas-project/lavas#83]
# 问题描述 :

SPA 应用中HTTPS下静态文件带了参数不能访问，状况是带参数后会被重定向到error路由，不带参数则可以正常访问，

HTTP协议下没有此问题
# 环境：
SPA + HTTPS

# lavas版本：
2.0

# 重现步骤
静态文件后面带url参数 回车可复现

**Comment by easonyq** [comment]
首先，这是 service worker 引入导致的 BUG。

在访问 `static` 目录下的静态文件时，如果直接访问 （例如 `/static/some.html`）是正常的，但当加上参数后 （例如 `/static/some.html?a=1`），由于和 precache list 中不能**完全匹配**，因此 workbox 认定**没有命中**预缓存文件，被 lavas 自动追加的 `registerNavigationRoute` 捕获，错误地返回了单页入口 `index.html`，从而引发错误。

仅就这个 case，我们给出的**解决方案**是：

利用 workbox 构造函数提供的 `ignoreUrlParametersMatching` 参数，将开发者认定的业务相关的统计参数添加进来，告知 workbox 忽略这些业务参数，就能够命中 precache，也就不会掉落到 `navigationRoute` 了。如下：

```javascript
// core/service-worker.js
const workboxSW = new WorkboxSW({
    cacheId: 'lavas-cache',
    ignoreUrlParametersMatching: [/^utm_/, /^a/, /^b/],
    skipWaiting: true,
    clientsClaim: true
});
```

这里我们注册了两个参数 `a` 和 `b`。更进一步，开发者可以**根据自己项目的实际情况**，配置 `/./` 进行**完全匹配**，一劳永逸。

**Comment by easonyq** [comment]
上述方案可以解决问题，但 lavas 在整个过程中依然有可以提升的点。lavas 自动追加的 `registerNavigationRoute` 使得开发者丧失了部分灵活性，例如要为它配置 whitelist, blacklist 目前就无法实现。

因此通过这个 case ，我们打算将这句自动生成的语句改为条件判断：
如果开发者的模板 (`core/service-worker.js`) 中包含 `registerNavigationRoute`，则 lavas 不再生成这句语句。这样使得开发者使用黑白名单进行灵活配置，甚至多次配置都成为可能。
