### ISSUE TITLE
lavas-mpa中webpack3.0以上版本打包后出现部分样式丢失无法打包进css; TypeError: Cannot read property 'call' of undefined 

### ISSUE THREAD

**Issue by qq282126990** [lavas-project/lavas#85]
Tested with
webpack: ^3.5.4
Node: v8.4.0

**File setup**

     // 定义切割点，异步加载路由组
     let Home = () => import('@/pages/home/home.vue');
     let Find = () => import('./Find.vue');
     let My = () => import('./My.vue');`

以上设置会导致打包的时候部分样式丢失；可能是因为设置了异步加载路由所以导致webpack打包的时候把以上3个路由组件分别打包成了3个js文件,导致webpack css-loader无法统一打包

**最后不使用异步加载路由**

    import Home from '@/pages/home/home.vue';
    import Find from '@/pages/home/Find.vue';
    import My from '@/pages/home/My.vue';

TypeError: Cannot read property 'call' of undefined报错成功解决

**Comment by xiaoiver** [comment]
在**生产环境**同时使用**异步加载路由**会出现这个问题，原因是 Lavas 使用了 extract-text-webpack-plugin 这个插件从 JS 中分离样式，这一步会把 css-loader 中异步加载样式的代码删除。而使用异步加载路由组件时，又需要这部分代码，所以会出错。[相关 ISSUE](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/456)

解决办法是把 `vue-style-loader/lib/addStylesClient` 和 `css-loader/lib/css-base` 这两部分代码也打包到 `vue` 这个 chunk 里。

**Comment by xiaoiver** [comment]
上面的 [ISSUE](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/456) 描述的就是这个问题。

首先 Lavas 2.x 不存在这个问题。原因是我们已经使用 CommonChunkPlugin 将 node_modules 下使用到的第三方依赖都打包到了 vendor 中，自然也包括了这两个 `vue-style-loader/lib/addStylesClient` 和 `css-loader/lib/css-base`。

而 Lavas 1.x 也就是你使用的 MPA 模板中，使用了 multipage-webpack-plugin 插件为每一个 entry 生成对应的 HTML。其中 CommonChunkPlugin 的配置也是由这个插件完成的，[相关代码](https://github.com/mutualofomaha/multipage-webpack-plugin/blob/master/src/plugin.js#L69-L84)。而这个插件又没有提供修改这一行为的方法，所以要解决这个问题，你可以开启 `allChunks`，这样会把所有样式都分离出来，相比异步 chunk 的样式是由 JS 异步加载，样式表会增大，但相应的，异步 chunk 体积会变小。
```javascript
// webpack.prod.js

        new ExtractTextPlugin({
            filename: utils.assetsPath('css/[name].[contenthash].css'),
            allChunks: true
        }),
```
