### ISSUE TITLE
doc: lavas-core-vue 能否增加readme.md文件

### ISSUE THREAD

**Issue by xtx1130** [lavas-project/lavas#86]
* **Version**: master
* **Platform**: all
* **Subsystem**:doc

`lavas-core-vue`作为单独的包能提供哪些方法？是否可以越过`lavas-cli`直接接入`lavas-core-vue`？能否针对`lavas-core-vue`增加一份说明文档，目前在官网或者git上没看到`lavas-core-vue`有关的文档。

**Comment by xiaoiver** [comment]
目前模板中的 `server.dev.js` 和 `server.prod.js` 这两个脚本其实就是在使用 lavas-core-vue。lavas-cli 做的只是提供一些命令，例如 `lavas dev` 等，调用这些脚本。

目前你可以参考一下材料：
[lavas-core-vue API](https://lavas.baidu.com/guide/v2/advanced/core-api)
[Codelab: 以编程方式使用 Lavas](https://lavas.baidu.com/codelab/core-api/01introduction)

我们会继续完善文档和教程，欢迎提出建议。

**Comment by easonyq** [comment]
我来为文档添加一段和 `lavas-cli` 无关的，调用 `lavas-core-vue` 进行开发调试和构建的方法说明
