### ISSUE TITLE
为什么不用eslint，为什么不用element-ui

### ISSUE THREAD

**Issue by SteveCruise** [lavas-project/lavas#9]
搞技术选型的人是不是可以撤了

**Comment by PengXing** [comment]
1. 我们用了 [fecs](https://github.com/ecomfe/fecs) 来做代码规范校验，fecs 基于 eslint 做了封装，而且还能校验 css html，所以效果是一样的
2. 为什么要用 element-ui? 我们选择的是 Google 的 [Material Design](https://material.io/)，而 element-ui 不是基于 Material Design 的开发的组件库

**Comment by SteveCruise** [comment]
谢谢回答，我的意思是选了两个相对冷门的配件，把想入坑的人搞蒙了

**Comment by PengXing** [comment]
嗯，是会有一点吧，我们在文档上也写了这些，可能还不够突出。Material Design 在国外很火，很多 Vue 的组件都是基于 Material Design 来做的。
